### ISSUE TITLE
Is Android version 4.4 supported by TF light?

### ISSUE THREAD

**Issue by n33lkanth** [tensorflow/tflite-micro#1123]
Hi,
I need to deploy a classifier to an edge device using TF light. The device has Android 4.4.2 version installed and uses Java version 7.
Is it possible to install the TF light model to this device?
Also, where can I check this compatibility related detail?

Best Regards,

**Comment by rockyrhodes** [comment]
Sorry, this is the repo for TF Lite for Microcontrollers. Regular TFLite supports android deployments. Please see the resources referenced here for more help: https://www.tensorflow.org/lite
