### ISSUE TITLE
Add support for the DIV op

### ISSUE THREAD

**Issue by sasapetr** [tensorflow/tflite-micro#1190]
This issue is to track efforts to port the reference DIV kernel from TF Lite to TFLM.  Some work has already been done in https://github.com/tensorflow/tensorflow/issues/45431, but it seems that it was not fully ported.

 https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/porting_reference_ops.md explains the steps to follow.

**Comment by JustinOng** [comment]
It seems like the DIV kernel was fully merged into TFLM, but it was removed in tensorflow/tensorflow#48198. I can't find any other reference to `184059002` to explain why it was removed either.
