### ISSUE TITLE
Xtensa optimized kernels for add and mul

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tflite-micro#122]
As noted in https://github.com/tensorflow/tflite-micro/pull/115#pullrequestreview-674750771 we will need some refactoring prior to adding in optimized implementations for add and mul for Xtensa.

This will include refactoring the reference and cmsis_nn kernels and then adding the Xtensa kernels with optimized calls for Hifi5 and reference fallback for all other target architectures.

**Comment by advaitjain** [comment]
tagging @bhanuprakashbv

**Comment by bhanuprakashbv** [comment]
@advaitjain, please let me know is there any action item for me related to refactoring the reference kernels.
If so, we can discuss via email.

Along with mul, add activations operators, I am planning to raise pull request for other hifi5 operators as well.
Do we need to refactor for these reference kernels as well?
