### ISSUE TITLE
Person Detection and Micro Speech didn't work together

### ISSUE THREAD

**Issue by onderbedirhan** [tensorflow/tflite-micro#1230]
I want to use Person Detection and Micro Speech example on my nRF 52840 boards. But created these two projects ram usage increased a lot and BLE not worked. So that I think, Person Detection and Micro Speech projects use same tensor arena and tensor arena size(use person detection tensor arena because this more than voice detection tensor arena) because ı dont want to run these projects same time. But due to constexpr variable type I didnt worked together. How I solve this problem ? 

Person Detection Example Namespace 
```
namespace pd {
tflite::ErrorReporter* error_reporter = nullptr;
const tflite::Model* model = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input = nullptr;
constexpr int kTensorArenaSize = 136 * 1024;
static uint8_t tensor_arena[kTensorArenaSize];
} 
```
Person Detection Example Static Interpreter
```
  static tflite::MicroInterpreter static_interpreter(
      pd::model, micro_op_resolver, pd::tensor_arena, pd::kTensorArenaSize, pd::error_reporter);
```
Microspeech Example Namespace
```
namespace vd{
tflite::ErrorReporter* error_reporter = nullptr;
const tflite::Model* model = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* model_input = nullptr;
FeatureProvider* feature_provider = nullptr;
RecognizeCommands* recognizer = nullptr;
int32_t previous_time = 0;
constexpr int kTensorArenaSize = 10 * 1024;
uint8_t tensor_arena[kTensorArenaSize];
int8_t feature_buffer[kFeatureElementCount];
int8_t* model_input_buffer = nullptr;
} 
```
Microspeech Example Static Interpreter
```
  static tflite::MicroInterpreter static_interpreter(
      vd::model, micro_op_resolver, vd::tensor_arena, vd::kTensorArenaSize, vd::error_reporter);
```

**Comment by petewarden** [comment]
You don't specify what the error message you're seeing is, so it's hard to know what's going wrong. Can you add that in?
