### ISSUE TITLE
Dilatation in conv2D not working as intended

### ISSUE THREAD

**Issue by invoxialdo** [tensorflow/tflite-micro#1231]
The issue concerns the use if conv2D including dilatation in tflite for microcontrollers. To test it, I used a very shallow model that only includes two convolutional blocks, each with one convolution, one activation. The only difference between the two convolutions is that the first one has a dilatation parameter of one, whereas the second has a dilatation parameter of two. The conversion to a tensorflow model, then to a cc file and its use to make inferences produced no error. But when comparing the result to the inference using the h5 file or the tflite file, it is not accurate at all. The issue appears to come from the dilatation parameter as the inference worked perfectly as soon as I set it to 1.

Here is the model to reproduce the issue :

```
nlayers = 4
dilatations = [1, 2]
filters = [12, 12]
kernels = [3, 3]
paddings = ['valid', 'valid']
strides = [2, 2]
act='relu'
usebias=True

convlay = SeparableConv2D
convname = 'separable_conv2d'


input_tensor = Input(shape = (INPUT_SIZE, 1, 3))

x = input_tensor

for l in range(2):
    x = convlay(filters[l], (kernels[l], 1), strides=strides[l],
                dilation_rate=dilatations[l], padding=paddings[l], use_bias=True
                )(x)
    x = Activation(act, name='activation_%i' % (l + 1))(x)

x = convlay(9, (6, 1), use_bias=True, name='head1')(x)
# x = Activation('softmax', name='headact')(x)
x = GlobalAveragePooling2D(name='head_GAP')(x)
model = Model(input_tensor, x)
```

**Comment by Yaxit** [comment]
I also have issues with the dilation currently. Network output on the MCU does not match the expected one from the python interpreter. I'm using full int8 quantization currently.
When I use dilation=1 the output is correct.
