### ISSUE TITLE
Makefile doesn't build hello_world binary

### ISSUE THREAD

**Issue by joeb42** [tensorflow/tflite-micro#1236]
When I run 
`make -f tensorflow/lite/micro/tools/make/Makefile hello_world_bin `
I get: 
`No rule to make target 'tensorflow/lite/micro/tools/make/gen/osx_x86_64_default/obj/core/tensorflow/lite/micro/examples/hello_world/main.o', needed by 'tensorflow/lite/micro/tools/make/gen/osx_x86_64_default/bin/hello_world' `
The error is the same when replacing hello_world_bin with hello_world. hello_world_test works as expected. The other examples magic_wand and person_detection work as expected. I'm on a Mac (OSX 10.15.7).

**Comment by KHIEM2812** [comment]
have u tried with bazel?
