### ISSUE TITLE
small mistake in the size of the models in train_hello_world_model.ipynb notebook

### ISSUE THREAD

**Issue by Bechir-Brahem** [tensorflow/tflite-micro#1240]
In the file tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb
the tensorflow model size is determined by this code
```python
size_tf = os.path.getsize(MODEL_TF)
```
while it works for the tfilte files it does not work for `MODEL_TF` because it is a folder. As you can see in the related picture this function returns 4096 (the size of metadata used by a directory in linux) 
![image](https://user-images.githubusercontent.com/54041290/177041648-7b215f4a-6091-4660-9ebf-2918812c5a98.png)

I will submit a pull request to fix this.
Thank you

**Comment by ddavis-2015** [comment]
You may find the following useful in creating your PR: https://github.com/tensorflow/tflite-micro/pull/1385/files

This change was made to the automatable training script.
