### ISSUE TITLE
Quantization increase interpreter time?

### ISSUE THREAD

**Issue by Mudzzh** [tensorflow/tflite-micro#1266]
I encountered a problem using the tensorflow quantization tool. I performed model inference after model quantization, but the inference time was greatly increased. I want to know why this is, I converted the original model to a tflite model (not quantized) its inference time is normal, but after performing quantization, the inference time of the model increases from 5s to 200s, which confuses me so much.

without quantization:
        # Converter
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        tflite_model = converter.convert()
with quantization:
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        tflite_model_quant = converter.convert()

use the interpreter.invoke() to interpreter the model .
this block is how i evaluate my model

# Evaluate the mode
  start_time = time.time()
  input_index = interpreter.get_input_details()[0]["index"]
  output_index = interpreter.get_output_details()[0]["index"]

#Run predictions on every image in the "test" dataset.
  prediction_digits = []
  for test_image in X_test:
    # Pre-processing: add batch dimension and convert to float32 to match with
    # the model's input data format.
    test_image = np.expand_dims(test_image, axis=0).astype(np.float32)
    test_image = np.expand_dims(test_image, axis=2).astype(np.float32)
    interpreter.set_tensor(input_index, test_image)
# Run inference.
    interpreter.invoke()

[tflite_models.zip](https://github.com/tensorflow/tflite-micro/files/9156008/tflite_models.zip)

**Comment by amkmpro** [comment]
Hi, what device do you run it on?

**Comment by Mudzzh** [comment]
> 

Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by Mudzzh** [comment]
> Hi, what device do you run it on?

Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by rkuester** [comment]
Hi @Mudzzh, may I suggest you ask this question in the upstream [TensorFlow discourse forum](https://discuss.tensorflow.org), as the behavior you're reporting has more to do with TensorFlow Lite in general than with Tensorflow Lite **for Microcontrollers**, the subject of this particular repository.
