### ISSUE TITLE
how about the INT4 support in TFLM

### ISSUE THREAD

**Issue by Howard9112** [tensorflow/tflite-micro#1272]
In some requirement, the INT8 still cannot meet the performance requirement, so I want to use the INT4 in ops, like conv2d. But in the type definition "TfliteType", I don't find the INT4. So I don't know how to do it if I use the INT4 weight + INT4 activation. Thank you in advance。

**Comment by rkuester** [comment]
Assigning to @advaitjain, who indicated a desire to comment on this issue.
