### ISSUE TITLE
How to build for SparkFun Edge in Windows?

### ISSUE THREAD

**Issue by Aztec02** [tensorflow/tflite-micro#1321]
Can this repo be build in Windows for Sparkfun Edge? And if yes are there are any valid guidelines?

**Comment by advaitjain** [comment]
We don't directly support specific hardware targets from the current repository but do provide the hooks to allow you to integrate TFLM into your dev environment. The following links may be helpful:
 * https://github.com/tensorflow/tflite-micro#community-supported-tflm-examples
 *  https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/new_platform_support.md
 * https://github.com/advaitjain/tflite-micro-sparkfun-edge-examples/
