### ISSUE TITLE
No interface class for MicroProfiler

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tflite-micro#1336]
This feature https://github.com/tensorflow/tflite-micro/commit/4a8320a72772dba3190570b9b9163b0db86bc37f may signicantly increase stack usage or memory footprint for projects even not using the feature. A profiler class that inherits from MicroProfiler will increase it's size even though it can not access the array since it is private to MicroProfiler.
One option to remedy this could be to add a new Profiler inheriting from MicroProfiler with the additonal CSV log feature (calling it ExtendedMicroProfiler), and place for more features. However even better would be to have an abstract base class for MicroProfiler, with BeginEvent/EndEvent that MicroProfiler inherits from. Projects would then have the option to only override this interface profiler class. 
@advaitjain @tanmaydas82 What do you think?

**Comment by advaitjain** [comment]
Having an interface class sounds good to me. We can start with what you have in #1376 and see if the interface needs to be made richer in the future.
