### ISSUE TITLE
Didn't find op for builtin opcode 'RFFT2D' version '1'

### ISSUE THREAD

**Issue by MATTYGILO** [tensorflow/tflite-micro#1401]
Hi I am getting this error when tiny to load in tflite file with FFT functionality. I am basically trying to create a stft that is a replicate of [scipy's stft](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html).

> Didn't find op for builtin opcode 'RFFT2D' version '1'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?
> 
> Failed to get registration from op code RFFT2D
>  
> AllocateTensors() failed!

This is my model in Netron

![stft](https://user-images.githubusercontent.com/34808802/188319742-8c8c131c-db7c-438c-9a48-5a034620413c.png)

**Comment by saleh1shalabi** [comment]
Hey! I'm facing same problem as you, have you been able to solve it?
