### ISSUE TITLE
LSTM kernel in TFL and TFLM use different tanh and sigmoid 

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tflite-micro#1455]
The LSTM kernel in TFL and TFLM use different implementations of tanh and sigmoid that are not bit exact.

See here for TFLM:
https://github.com/tensorflow/tflite-micro/blob/5818e46c78fcce795077c119336265dcacc0bf70/tensorflow/lite/micro/kernels/lstm_eval.cc#L537
https://github.com/tensorflow/tflite-micro/blob/5818e46c78fcce795077c119336265dcacc0bf70/tensorflow/lite/micro/kernels/lstm_eval.cc#L626

And TFL:
https://github.com/tensorflow/tensorflow/blob/d415e0d8f95d2250322035e396c35020c45281bc/tensorflow/lite/kernels/lstm_eval.cc#L588
https://github.com/tensorflow/tensorflow/blob/d415e0d8f95d2250322035e396c35020c45281bc/tensorflow/lite/kernels/lstm_eval.cc#L668

**Comment by UlrikHjort** [comment]
@vdkhoi @SebastianBoblest FYI

**Comment by mansnils** [comment]
Merging this PR to TFL would resolve the issue:  https://github.com/tensorflow/tflite-micro/pull/1253
