### ISSUE TITLE
Failed to allocate tail memory. Requested: 2088, available 1552, missing: 536

### ISSUE THREAD

**Issue by cucbui57** [tensorflow/tflite-micro#1458]
@tensorflow/micro

**System information**

Testing LoadModelAndPerformInference
Failed to allocate tail memory. Requested: 2088, available 1552, missing: 536
Failed to allocate memory for context->eval_tensors, 2088 bytes required
Failed starting model allocation.

interpreter.AllocateTensors() == kTfLiteOk failed at tensorflow/lite/micro/examples/hello_world/hello_world_test.cc:58 (1 vs 0)
make: *** [tensorflow/lite/micro/examples/hello_world/Makefile.inc:37: test_hello_world_test] Segmentation fault

**Describe the problem**
I have an error when run my model by command line: 
`make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test`

**Comment by kisielk** [comment]
You probably need to increase the size of the arena you are passing to the interpreter
