### ISSUE TITLE
Create a Python distribution package

### ISSUE THREAD

**Issue by rkuester** [tensorflow/tflite-micro#1484]
# Create a Python distribution package

This is a proposal for creating a TFLM Python package.

## Vision

The Python bindings of the TFLM interpreter are difficult to use in situ, from
their location in the TFLM source tree. By building a package, we allow users to
install and then use TFLM via Python in any virtual or real environment,
independently of the TFLM source tree, the same way they would use any package,
including Tensorflow and Tensorflow Lite.

While TFLM's target application is running on microcontrollers in C, of course,
running in Python on x86_64 is useful during development. Running in Python is
useful for quick prototyping and testing in its own right, and especially
powerful because it allows TFLM to be used directly alongside Tensorflow and
Tensorflow Lite within a Python environment. E.g., you can create a model with
Keras, run it through TFLM and Lite in parallel, and compare the outputs---all
from one short Python script.

Beyond the usefulness of installation from a local source tree, additional use
cases can be enabled by publishing the package to PyPI, including use from from
Colab and use on x86_64 without first building from Bazel.

## Design

Name the distribution package `tflite-micro` to match our project naming in
GitHub and elsewhere. In Python, that translates to the package name
`tflite_micro`, note the underscore.

Distribute only one package `tflite-micro` containing both code designed for
runtime like the TFLM interpreter and development-only code like tools for
manipulating models. Perhaps a reason to seperate the use cases into distinct
packages will emerge in the future, but for now, keep it simple and follow in
the footsteps of Tensorflow proper, which releases one omnibus package.

Within the source tree, add a `//python/` directory at the root and begin
refactoring our packagable Python code into it. For compatibility with the
Python tools, the directory structure underneath should reflect the physical
structure of the distributable package---i.e., a `//python/tflite_micro/`
directory, representing our [implict namespace
package](https://peps.python.org/pep-0420/) `tflite_micro`, containing
subpackages and modules within, such as `//python/tflite_micro/runtime.py`.

        └── python/
            └── tflite_micro/
                ├── examples/
                │   └── hello.py
                ├── runtime.py     # containing class Interpreter
                └── signal/        # pre- and post-porcessing layers
                    └── rfft.py
    
Where it makes more sense to locate distributable Python code elsewhere in the
source tree, e.g., in proximity to C code it wraps, the Python code can be
collected underneath the packaging directory at build time.

This organization leads to names in Python such as `tflite_micro.runtime.Interpreter`.

## Publishing to PyPI

Publishing to PyPI is straightforward from CI. PyPI accounts are easily created,
package names are claimed on a first-come first-serve basis, and authentication
of the uploader can be performed via a secret token stored in GitHub.

Packages built in CI could be pushed nightly to PyPI. PyPI retains all versions.
Installation tools such as `pip` can optionally install versions other than the
latest. Package versions should adhere to [PEP
440](https://peps.python.org/pep-0440/).

**Comment by rkuester** [comment]
Reviving.

**Comment by skroedel** [comment]
Thanks for these changes @rkuester ! Is it already possible to build/install the python package at the current stage?

**Comment by rkuester** [comment]
> Thanks for these changes @rkuester ! Is it already possible to build/install the python package at the current stage?

You're welcome, @skroedel! Yes, it's a work in progress, but—in *main* today—the package should install and work on the machine on which it is built. pip install the .whl in the `bazel-bin/python/tflite_micro/whl_dist` directory that results from building the target `//python/tflite_micro:whl.dist`.

Improvements and documentation to come. Feedback welcome! Curious to hear if you try it.

For example:

```bash
% git checkout main
Your branch is up to date with 'tflm/main'.
% bazel build //python/tflite_micro:whl.dist
Starting local Bazel server and connecting to it...
INFO: Analyzed target //python/tflite_micro:whl.dist (112 packages loaded, 14829 targets configured).
INFO: Found 1 target...
Target //python/tflite_micro:whl.dist up-to-date:
  bazel-bin/python/tflite_micro/whl_dist
....
% ls bazel-bin/python/tflite_micro/whl_dist
tflite_micro-0.1.0-py3-none-any.whl
% # enter a venv
(venv) $ pip install bazel-bin/python/tflite_micro/whl_dist/tflite_micro-0.1.0-py3-none-any.whl
(venv) $ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_micro
>>> tflite_micro.postinstall_check.passed()
True
>>>  i = tflite_micro.runtime.Interpreter.from_file("foo.tflite")
>>> # etc.
```

**Comment by skroedel** [comment]
thanks yea that works perfectly. Thanks for the instructions.

**Comment by rkuester** [comment]
There's now a package in PyPI!

https://pypi.org/project/tflite-micro

For now, uploads to PyPI are ad hoc and manually run (using scripts in the tree), but soon we'll add automatic, periodic pushes via CI/CD.
