### ISSUE TITLE
TFLM code change introduced "%lu" which is not handled correctly by MicroVsnprintf (micro_profiler.cc) (PRIu32)

### ISSUE THREAD

**Issue by tcal-x** [tensorflow/tflite-micro#1494]
In this line in `micro_profiler.cc`:
```
    MicroPrintf("%d,%s,%" PRIu32, i, tags_[i], ticks);
```
`PRIu32` is `lu` on my system (riscv32 toolchain), resulting in a format specification of `%lu`.   However, the output lines look like this:
```
7,DEPTHWISE_CONV_2D,lu
```
that is, the `%lu` is just printed as "`lu`"; the substitution does not take place.

It seems the underlying issue is in MicroVsnprintf().

**Comment by advaitjain** [comment]
Sorry for the long delay on this. https://github.com/tensorflow/tflite-micro/pull/1876 has made this change.

**Comment by tcal-x** [comment]
Hi @advaitjain , ah, I did miss that (and yes, I didn't try retesting before sending my last comment).    Cheers!
