### ISSUE TITLE
Calculate FLOPS for tflite format models

### ISSUE THREAD

**Issue by tiendatAI** [tensorflow/tflite-micro#1509]
Hi,
I'm trying to estimate FLOPS of given tflite models, but unfortunately, I can not find any available source code or references for this task. How can I do this? Thank for your reply.

**Comment by ASabovic** [comment]
Have you ever found a way how to do this @tiendatAI? I am also trying to calculate flops for person detection models (including the tinyML model), but still struggling to get the right results :)
