### ISSUE TITLE
Using tf.signal.stft with tflite-micro

### ISSUE THREAD

**Issue by rgroh1996** [tensorflow/tflite-micro#1510]
Hi, 
I use the method tf.signal.stft as a preprocessing layer in my neural network. This works fine. However, when I convert it to tflite and use it on my microcontroller, it doesn't work because some ops are missing (e.g. the RANGE op). Does anyone know another STFT-TensorFlow layered implementation (I already know the STFTTflite implementation from the kapre library, but it doesn't seem to be very optimized)? Otherwise, it would be really great if it was possible to use tf.signal.stft directly without any workarounds. Thanks already for your answers and help!

**Comment by umgefahren** [comment]
Yes that would be great, but I just implemented the stft function myself using the esp-dsp library.
