### ISSUE TITLE
Compile with Armclang V6

### ISSUE THREAD

**Issue by shixin627** [tensorflow/tflite-micro#1540]
When I try to use armclang v6.18 to compile my RT-Thread project with TensorflowLite package, it couldn't find the files in the path(C:\Keil_v5\ARM\ARMCLANG\include\libcxx) and existed some C++ syntex error(I known this package was writen in c++11).
Can you show any clue for me to figure out these problems. THX!!
![image](https://user-images.githubusercontent.com/48245812/200727155-7e77fbfa-f483-4c8b-b4ed-78ecac8d384e.png)
![image](https://user-images.githubusercontent.com/48245812/200728381-51df5c14-ae5e-4686-ba75-1f83a451450e.png)

**Comment by UlrikHjort** [comment]
Seems you are compiling with a C compiler and not a C++ compiler

**Comment by shixin627** [comment]
You're right. I got the idea to figure out this problem, thank you.
