### ISSUE TITLE
Couldn't load person.tflite model with tf.lite.interpreter

### ISSUE THREAD

**Issue by Ramsonjehu** [tensorflow/tflite-micro#1555]
Hi, 
I tried loading the [person_detect.tflite model](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/models/person_detect.tflite) with tf.lite.interpreter, using the following code:

`import tensorflow as tf`
`interpreter = tf.lite.Interpreter(model_path='person_detect.tflite')`

But was hit with the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/generate_cc_array.ipynb Cell 5 in <cell line: 1>()
----> [1](vscode-notebook-cell:/home/generate_cc_array.ipynb#W5sZmlsZQ%3D%3D?line=0) interpreter = tf.lite.Interpreter(model_path='person_detect.tflite')
      [2](vscode-notebook-cell:/home/generate_cc_array.ipynb#W5sZmlsZQ%3D%3D?line=1) interpreter.allocate_tensors()
      [4](vscode-notebook-cell:/home/generate_cc_array.ipynb#W5sZmlsZQ%3D%3D?line=3) input_details = interpreter.get_input_details()[0]

File ~/virtual_environments/utkface/lib/python3.10/site-packages/tensorflow/lite/python/interpreter.py:455, in Interpreter.__init__(self, model_path, model_content, experimental_delegates, num_threads, experimental_op_resolver_type, experimental_preserve_all_tensors)
    448 custom_op_registerers_by_name = [
    449     x for x in self._custom_op_registerers if isinstance(x, str)
    450 ]
    451 custom_op_registerers_by_func = [
    452     x for x in self._custom_op_registerers if not isinstance(x, str)
    453 ]
    454 self._interpreter = (
--> 455     _interpreter_wrapper.CreateWrapperFromFile(
    456         model_path, op_resolver_id, custom_op_registerers_by_name,
    457         custom_op_registerers_by_func, experimental_preserve_all_tensors))
    458 if not self._interpreter:
    459   raise ValueError('Failed to open {}'.format(model_path))

ValueError: quantized_dimension must be in range [0, 1). Was 3.Tensor 33 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 36 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 40 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 44 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 48 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 52 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 56 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 60 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 64 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 68 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 72 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 76 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 80 has invalid quantization parameters.quantized_dimension must be in range [0, 1). Was 3.Tensor 84 has invalid quantization parameters.

**Tensorflow version : 2.9.1
Python version: 3.10.4**

How to solve this issue? Please guide 

Thanks

**Comment by biu-biu-002** [comment]
I have same issue!

Please guide
Thanks!
