### ISSUE TITLE
Hybrid models are not supported on TFLite Micro

### ISSUE THREAD

**Issue by Incomprehensible** [tensorflow/tflite-micro#1556]
Hi, I've encountered the following error trying to invoke the .tflite model I've loaded:
```shell
tensorflow/lite/micro/kernels/cmsis_nn/conv.cc Hybrid models are not supported on TFLite Micro.
Node CONV_2D (number 1) failed to invoke with status 1
interpreter->Invoke() failed
```
Does it mean that my .tflite model must be fully quantized for the current version of the tflite-micro?

I'm using the microlite library built for the cortex_m_generic target, with target architecture cortex-m7+fp and CMSIS_NN support.
The model was built using the Tensorflow 2.8 version.
My model's format is TensorFlow Lite v3.
Input tensor format is: float32[1,64,1]
Output format: float32[1,2,64]
I'm using the latest version of tflite-micro, commit aba71897cc518522cf4f52634d97079e9fc8024b

**Comment by Teven1111** [comment]
你怎么解决的？我也遇到了类似的问题
