### ISSUE TITLE
armclang does not support option -Wno-stringop-overread

### ISSUE THREAD

**Issue by annietllnd** [tensorflow/tflite-micro#1571]
Hi, the changed added for #1544 omits the Arm(R) Cortex(R)-M-based builds, which adds the flag and as a result introduces an error it's not valid for armclang. I'm going to submit a PR which adds the Cortex-M builds to to list which is exempted from the added flag. 

For reference, this topic is also mentioned in #1337 

Thanks,
Annie

**Comment by t4i5m6** [comment]
Hi, I met this problem too when I tried to make test_hello_world_test  with my Macbook with M2 chip.

error: unknown warning option '-Wno-stringop-overread' [-Werror,-Wunknown-warning-option]
make: *** [tensorflow/lite/micro/tools/make/Makefile:651: gen/osx_arm64_default/obj/core/tensorflow/lite/micro/examples/hello_world/hello_world_test.o] Error 1

Thanks,
Tim
