### ISSUE TITLE
Question about image conversion in person detection example

### ISSUE THREAD

**Issue by wuruoyu** [tensorflow/tflite-micro#161]
Hi,

I want to use my own image to test [person detection](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/person_detection) so I need to convert my images to a (96 * 96) C array. I follow the instructions below, but the byte array I get is too long. 
https://github.com/tensorflow/tflite-micro/blob/f583f92992c3c9dfb8e10f36d66b2fe7267cf7bc/tensorflow/lite/micro/examples/person_detection/person_image_data.h#L17-L20

For instance, I test it with my Github avatar:
![avatar](https://user-images.githubusercontent.com/12579777/121604861-512f9c80-ca19-11eb-8347-7247e8470854.png)

Here are the instructions I use to generate C array file
1. convert -colorspace Gray avatar.png avatar_g.png (to convert it to grayscale img)
2. convert -resize 96x96\! avatar_g.png avatar.bmp3
3. xxd -s 54 -i avatar.bmp3 > avatar.cc

The result C array is of length 27648 (96 * 96 * 3) I do not figure out how to convert it to single-channel since the expected input is (96 * 96). I tried but failed. Could you help take a look at this and update the instructions? Thanks in advance!

**Comment by alanvgreen** [comment]
You might try asking on an imagemagick forum. The exact sequence of commands is dependent on the version of imagemagick (the "convert" command) that you are using.

**Comment by petewarden** [comment]
Closing, since I believe this is outside the scope of the project.
