### ISSUE TITLE
On WSL, I am unable to make a project using the arm toolchain. 

### ISSUE THREAD

**Issue by phuoctan4141** [tensorflow/tflite-micro#1615]
I can't complete this project with the current version. However, on the old version from two months ago, this project could be successful.
![Screenshot_20221208_113544](https://user-images.githubusercontent.com/16333797/206749600-937027d3-4cbd-4308-b0c6-5a914dc0b829.png)
![Screenshot_20221202_112922](https://user-images.githubusercontent.com/16333797/206750294-fa8e78b1-e77b-445a-af7d-291ce0a287a1.png)

**Comment by mansnils** [comment]
Hi @phuoctan4141 
Thanks for reporting this, we will look into it.

**Comment by mansnils** [comment]
Hi @phuoctan4141 

Did you mean TARGET=cortex_m_corstone_300 instead TARGET=cortex_m_generic?

The TARGET=cortex_m_generic is just meant to build the micro lib and then link this to the application outside of TFLM.
So it has no support for building any unit test or example test within TFLM.
For that the TARGET=cortex_m_corstone_300 could possible be used instead.

So I don't think this has ever worked:
make -j 4 -f tensorflow/lite/micro/tools/make/Makefile OPTIMIZED_KERNEL_DIR=cmsis_nn TARGET=cortex_m_generic TARGET_ARCH=cortex-m0plus  hello_world

You can also see the tests for these targets:

https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/ci_build/test_cortex_m_corstone_300.sh
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/ci_build/test_cortex_m_generic.sh

**Comment by mansnils** [comment]
Could you elaborate on this project?

It looks like you are using CMake. The internal examples in TFLM does not use CMake.

**Comment by phuoctan4141** [comment]
I could fix all program. Thanks for your support.
