### ISSUE TITLE
Cannot open create_sine_model.ipynb

### ISSUE THREAD

**Issue by tinyBrkML** [tensorflow/tflite-micro#1632]
I am going to the link that was posted in [this](https://github.com/tensorflow/tensorflow/issues/39362) discussion. However, when I open the link, it can't open the file. I also can't find create_sine_model.ipynb anywhere else. 
![Screenshot 2022-12-21 125824](https://user-images.githubusercontent.com/120507146/208976168-03530654-7b3f-486e-843f-9a720146d818.png)

**Comment by ddavis-2015** [comment]
The file has moved to here: https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb
