### ISSUE TITLE
create_tflm_tree.py fails 

### ISSUE THREAD

**Issue by subrockmann** [tensorflow/tflite-micro#1644]
I am trying to create a new project with the following code because I need the "network_tester" example: 

```
python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py /mnt/i/tinyml/tiny_vision_mcu/network_tester --print_src_files -e hello_world e- network_tester
```

Unfortunately, this fails with the following error:

```
RuntimeError: make -f tensorflow/lite/micro/tools/make/Makefile list_network_tester_example_sources TENSORFLOW_ROOT= failed with 

 tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/kissfft already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
find: ‘tensorflow/lite/micro/tools/gen_micro_mutable_op_resolver_test/person_detect’: No such file or directory
```

While the skipped downloads are totally fine, I am wondering why "tensorflow/lite/micro/tools/gen_micro_mutable_op_resolver_test/person_detect" is mentioned, because this file belongs to one of the examples that I did not specify.

Thanks for your support.

**Comment by rkuester** [comment]
Hi @subrockmann, does the code in PR #1726 get you what you want? It exports a basic set of files for network_tester; however, I did nothing to test the exported tree is useful. If it's not quite right, perhaps you can expand on what I started.

(The warning about the missing directory wasn't the root of the issue.)
