### ISSUE TITLE
tflite-micro-arduino-examples: micro_test.h is missing

### ISSUE THREAD

**Issue by subrockmann** [tensorflow/tflite-micro#1664]
The [tflite-micro-arduino-examples](https://github.com/tensorflow/tflite-micro-arduino-examples) repository is missing the "testing" folder and therefore "micro_test.h".    
The [Get started with microcontrollers](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level) documentation uses [hello_world_test.cc](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/hello_world_test.cc) for the general introduction. It would be extremely helpful for new users to be able to follow these examples also on Arduino. Having the testing framework available in the Arduino library would also be a useful feature.

**Comment by ddavis-2015** [comment]
Thank you for your interest in TFLM, we appreciate your feedback.

The [Get started with microcontrollers](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level) document and the associated hello_world_test application are designed for use only with the tflite-micro repository.  The tflite-micro repository is setup for use by those comfortable with using command-line interfaces and makefiles.

The tflite-micro-arduino-examples repository was created to provide a point-and-click method for demonstrating TFLM examples on actual hardware.  This purpose of this repository is primarily to show how to use a TFLM application with a physical microcontroller (as opposed to emulators/simulators), in the easiest way possible using the Arduino IDE.  As such, we do not support any unit tests within this repository.
