### ISSUE TITLE
generating the tflm build files for mbed breaking with create_tflm_tree.py

### ISSUE THREAD

**Issue by kumarchaitanyab** [tensorflow/tflite-micro#1705]
Hi Team, am trying the generate the tflm build (2.8.0) to be used with mbed environment using create_tflm_tree.py file and it is breaking with below error.

I used below to generate the build. Not sure how to fix this issue and need inputs on addressing this.
"python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py --makefile_options="TARGET=cortex_m_generic TARGET_ARCH=cortex-m4+fp  OPTIMIZED_KERNEL_DIR=cmsis_nn TARGET_TOOLCHAIN_ROOT=/opt/gcc-arm-none-eabi-9-2020-q2-update/bin/ TARGET_TOOLCHAIN_PREFIX=arm-none-eabi- " tflm-tree 

Traceback (most recent call last):
  File "tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py", line 303, in <module>
    main()
  File "tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py", line 293, in main
    _copy(src_files, dest_files)
  File "tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py", line 124, in _copy
    shutil.copy(src, dst)
  File "/home/pvasa/.conda/envs/embed_env/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/pvasa/.conda/envs/embed_env/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

**Comment by ddavis-2015** [comment]
Thank you for your interest in TFLM.  I have tested your command line for generating your project using a Ubuntu 18.04 system, and found no errors (the tree was generated successfully).

Did you have a full clone of the tflite-micro repository?  An example of the command to clone the tflite-micro repository is as follows: `git clone --depth 1 --single-branch "https://github.com/tensorflow/tflite-micro.git"`

This issue will now be closed.  Please feel free to reopen the issue should you wish to add further information.
