### ISSUE TITLE
`gather_nd`: prepare stage tries to access model `.rodata`

### ISSUE THREAD

**Issue by vikramdattu** [tensorflow/tflite-micro#1723]
model used: single_pose model from tf_hub:

Following lines from `gather_nd` OP in prepare stage try to update values from the actual model, which of course is problematic:

https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/gather_nd.cc#L92-L100

Related issue on `tflite-micro-esp-examples`: https://github.com/espressif/tflite-micro-esp-examples/issues/30#issuecomment-1410372797

I have simply commented out the lines locally. Please suggest correct path here.

**Comment by ddavis-2015** [comment]
@vikramdattu 

Thank you for bringing this issue to the attention of the TFLM team.  We appreciate your feedback regarding problems with the TFLM codebase.

This issue has been identified as a bug in the GATHER_ND kernel operator.  The PR #1727 has been submitted for this issue.  Once the PR is merged, this issue should automatically close.
