### ISSUE TITLE
Error: L6218E: Undefined symbol __clrsbsi2 (referred from div.o).

### ISSUE THREAD

**Issue by Raise-me-up** [tensorflow/tflite-micro#1757]
Hi! I use the arm-none-eabi-g++ and  arm-none-eabi-gcc to build the  libtensorflow-microlite.a, it is ok. However, when I try to compile the hello world source codes by armclang.exe(Arm C++ Compiler for Embedded 6), and link it with the library by armlink.exe, the error occurs during the link. Its messages are some confusing. What should I do to deal with the error? Thanks for your help!

**Comment by mansnils** [comment]
Hi @Raise-me-up,
Can you specify the build command to reproduce this?
