### ISSUE TITLE
Can't build on macOS due to tensorflow-cpu pip dependency

### ISSUE THREAD

**Issue by jmole** [tensorflow/tflite-micro#1781]
I've fixed this for the moment by Find->Replace **tensorflow-cpu** with **tensorflow-macos**, but maybe there is a better way to handle this in bazel?

**Comment by kismeter** [comment]
> I've fixed this for the moment by Find->Replace **tensorflow-cpu** with **tensorflow-macos**, but maybe there is a better way to handle this in bazel?

Did you observe the issue when Replace **tensorflow-cpu** with **tensorflow-macos** during the `bazel build tensorflow/lite/micro/examples/micro_speech:audio_preprocessor`?

**Comment by mansnils** [comment]
Seems we have a duplicate: https://github.com/tensorflow/tflite-micro/issues/2367
