### ISSUE TITLE
Encounter segment error when  trying to deploy tflite model

### ISSUE THREAD

**Issue by HJL8055** [tensorflow/tflite-micro#1784]
Hi,
I encountered segment error when I tried to deploy my tflite model.
Then, I found that error appeared while "AllocateTensors()"->"graph_.PrepareSubgraphs()"->"registration->prepare(context_, node)"
There, I printed the node id and registration->builtin_code.
Result list below.
![6ZKVS5~K@2TA58DN`FI0XIA](https://user-images.githubusercontent.com/66299911/220813113-40cb46e9-d93d-4959-a2a9-9439f218661b.png)
After using netron, the node 24 correspond to FullyConnected.
![LBAJ 2(1NTWX_(G~KOM3LL7](https://user-images.githubusercontent.com/66299911/220813419-ad2faa60-91bb-4fa3-9d15-de6ffc1e61da.png)
If I remove the AddFullyConnected() for micro_op_resolver, it shows the version of FullyConnected is verson'5'.
![)L2LKDGFEG 5QHLL VCP}MW](https://user-images.githubusercontent.com/66299911/220813694-2867a19e-082e-4776-a9b5-e76b32343d95.png)
I am not sure whether some preblems occur here.

**Comment by HJL8055** [comment]
Recently, I find that the error is raised by  the following code. 
TFLITE_DCHECK(filter->params.zero_point == 0);
This code restricts the zeropoints of the weight in fullyconnected-layer should always be zero.
![27M))K)C6~ ~Z1Y5J(O1Y0H](https://user-images.githubusercontent.com/66299911/222037215-98dc4a8b-1349-4f06-b702-f476e3027bf2.png)
But mine is -10 .
I wonder why my zeropoint is not zero while I use tensorflow-Post-training quantization-Full integer quantization to get my quantization_weight and it's hard for me to find the configure to restricts the zeropoints.

**Comment by karkapur** [comment]
Hi,

Has this error been addressed? I'm getting the same error and was wondering if someone has been able to figure this out.
