### ISSUE TITLE
Memory Management for Model object

### ISSUE THREAD

**Issue by Fatih-Kiralioglu** [tensorflow/tflite-micro#1814]
Hi,
I have read through memory_management.md document. In the document , there is an example like below:

```
// Buffer for the tensor arena:
size_t tensor_arena_size = 2048;
uint8_t tensor_arena[tensor_arena_size];

// Interpreter using the shared tensor arena above:
tflite::MicroInterpreter interpreter(
  tflite::GetModel(my_model_data), ops_resolver,
  tensor_arena, tensor_arena_size);

// Invoke one time which will allocate internals:
if (interpreter.Invoke() != kTfLiteOk) {
  MicroPrintf("Exception during invoke()!");
}
```
Do we need to manage the memory  of the Model * object created by  tflite::GetModel(my_model_data) or should we just leave it as it is throughout the lifetime of the application?

And  are we only responsible for the memory management of tflite::MicroInterpreter interpreter object?

**Comment by ddavis-2015** [comment]
The result of `tflite::GetModel()` does not need to be managed.  Internally, it is just a pointer to a location inside `my_model_data`.

You are responsible for the memory management of `my_model_data` and the instantiation of the `MicroInterpreter`.  Your `my_model_data` will typically be part of your program data, so there is nothing more you need to do.  The `interpreter` variable is typically declared `static` and a pointer to it assigned to a global variable so you can reference it elsewhere in your application:

```
tflite::MicroInterpreter* my_interpreter;

void main() {
...

// Interpreter using the shared tensor arena above:
static tflite::MicroInterpreter interpreter(
  tflite::GetModel(my_model_data), ops_resolver,
  tensor_arena, tensor_arena_size);

my_interpreter = &interpreter;

...
}
```
