### ISSUE TITLE
Compiling for Cortex M3 : How to reduce library size?

### ISSUE THREAD

**Issue by Ashwin-Rajesh** [tensorflow/tflite-micro#1815]
The TFLM website states "The core runtime just fits in 16 KB on an Arm Cortex M3 and can run many basic models.". 

However, when I compiled the library for ARM M3 using the following command

```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=cortex_m_generic TARGET_ARCH=cortex-m4+fp microlite -j8
```

The library size reported by arm-none-eabi-size is 372619 bytes. How can i reduce this to fit on my microcontroller? (TM4C123GH6PM with 256kB flash)

What are the build options and flags i can use? I was not able to find any documentation regarding this. Please add these to the base readme or the "porting to a new platform" pages.

**Comment by mansnils** [comment]
Build type could be change to release, which should improve size, BUILD_TYPE=release.
Also optimization flags could be change to -Os, keep in mind though that performance might be affected.
https://github.com/tensorflow/tflite-micro/blob/3eb56863879e2ba3c638ded56b89da99cc39cfa1/tensorflow/lite/micro/tools/make/Makefile#L118
