### ISSUE TITLE
Training notebook does not work

### ISSUE THREAD

**Issue by BitSalat** [tensorflow/tflite-micro#1821]
The training notebook has an issue with this statement:

`%tensorflow_version 1.x

import tensorflow as tf`

Info is:

Your notebook should be updated to use Tensorflow 2.
See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2.

**Comment by xandyxor** [comment]
https://github.com/tensorflow/tflite-micro/issues/1821
https://github.com/tensorflow/tflite-micro/issues/1690
https://github.com/tensorflow/tflite-micro/issues/1603
