### ISSUE TITLE
Getting to run tensorflow with a Teensy 4.1

### ISSUE THREAD

**Issue by cai49** [tensorflow/tflite-micro#1923]
I've been seeing that it can be possible to run tensorflow lite for mcus on the teensy but even after editing all the blockades that does not let me compile as it throws an exception, it just wont compile. Any ideas?

**Comment by ddavis-2015** [comment]
@cai49 

If you are looking to use a Teensy 4.1 with TFLM using Arduino, you may want to take a look at: https://github.com/ddavis-2015/tflite-micro-arduino-examples/tree/teensy-audio

This was a working version of TFLM using Arduino that runs on a Teensy 4.1 board.  The `hello_world` TFLM example should work just fine.  In particular, you will want to look at src/peripherals for the README and the peripherals.h file.  This use of TFLM with the Teensy 4.1 is 6 months out of date with the current TFLM codebase.

The above is not officially supported by Google or the TFLM team, and no official support for TFLM with the Teensy is being provided.
