### ISSUE TITLE
Outdated getting started tutorial

### ISSUE THREAD

**Issue by PawelLawrynowicz** [tensorflow/tflite-micro#1925]
[This](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level) tutorial has broken imports (and hyperlinks) due to #1560 where the MicroErrorReporter was moved from tensorflow/lite/micro/ to tensorflow/lite/micro/tflite_bridge

**Comment by mbernico** [comment]
As a newer TFLM user, I've noticed this as well.
