### ISSUE TITLE
generate_micro_mutable_op_resolver_from_model failing

### ISSUE THREAD

**Issue by gits00** [tensorflow/tflite-micro#1988]
Hi,

I am trying to build generate micro_mutable op_resolver from model using bazel.

Steps - 

1) Downloaded code from github
2) Tried -
   "bazel run tensorflow/lite/micro/tools/gen_micro_mutable_op_resolver:generate_micro_mutable_op_resolver_from_model -- --common_tflite_path=<xyz_dir> --input_tflite_files=xyz.tflite --output_dir=<xyz_dir>"

But getting below errors - 

ERROR: ............/external/tflm_pip_deps_markdown/BUILD.bazel:22:11: no such package '@tflm_pip_deps_importlib_metadata//': The repository '@tflm_pip_deps_importlib_metadata' could not be resolved: Repository '@tflm_pip_deps_importlib_metadata' is not defined and referenced by '@tflm_pip_deps_markdown//:pkg'
ERROR: Analysis of target '//tensorflow/lite/micro/tools/gen_micro_mutable_op_resolver:generate_micro_mutable_op_resolver_from_model' failed; build aborted: 
INFO: Elapsed time: 100.507s
INFO: 0 processes.
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (83 packages loaded, 12080 targets configured)
    Fetching repository @tflm_pip_deps_scipy; starting 6s
    Fetching repository @tflm_pip_deps_cachetools; starting
    Fetching repository @tflm_pip_deps_pyasn1_modules; starting
    Fetching repository @tflm_pip_deps_requests_oauthlib; starting
    Fetching repository @tflm_pip_deps_rsa; starting
    Fetching repository @tflm_pip_deps_urllib3; starting
    Fetching repository @tflm_pip_deps_charset_normalizer; starting
    Fetching repository @tflm_pip_deps_idna; starting

Tried below as well - 

bazel test tensorflow/lite/tools:flatbuffer_utils_test
ERROR: ............/external/tflm_pip_deps_markdown/BUILD.bazel:22:11: no such package '@tflm_pip_deps_importlib_metadata//': The repository '@tflm_pip_deps_importlib_metadata' could not be resolved: Repository '@tflm_pip_deps_importlib_metadata' is not defined and referenced by '@tflm_pip_deps_markdown//:pkg'
ERROR: Analysis of target '//tensorflow/lite/tools:flatbuffer_utils_test' failed; build aborted: 
INFO: Elapsed time: 0.591s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (1 packages loaded, 96 targets configured)
    Fetching repository @tflm_pip_deps_certifi; starting
    Fetching repository @tflm_pip_deps_charset_normalizer; starting
    Fetching repository @tflm_pip_deps_scipy; starting

But below is working -

bazel build tensorflow/lite/tools:visualize
INFO: Analyzed target //tensorflow/lite/tools:visualize (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow/lite/tools:visualize up-to-date:
  bazel-bin/tensorflow/lite/tools/visualize
INFO: Elapsed time: 42.372s, Critical Path: 23.46s
INFO: 127 processes: 79 internal, 48 linux-sandbox.
INFO: Build completed successfully, 127 total actions

python3 is Python 3.8.0, bazel release 6.2.0, Ubuntu 18.04.5 LTS. 

Am I missing something? Do I need to do something more before doing bazel run to get  micro_mutable op_resolver from model?

Thank you!

**Comment by mansnils** [comment]
I have also observed this error. It seems to be a quite recent problem. If stepping back a week in the main branch I don't think it is reproducible. Also I have not seen it with Python 3.10.

**Comment by JavaldeUB** [comment]
any news about this?
I have similar problem building evaluate in hellow_world example
J.

**Comment by mansnils** [comment]
If you can use Python 3.10 (?) that seems to solve it.

**Comment by ruggedman** [comment]
> If you can use Python 3.10 (?) that seems to solve it.

Still the same error with 3.10

**Comment by adityasahugit** [comment]
Please share if anyone resolved this, even I am getting the same error for hello world program, python 3.9
ERROR: /home/ubnew/.cache/bazel/_bazel_ubnew/4fedf9b6fe6c30a12c0a1d1252b5a39c/external/tflm_pip_deps_markdown/BUILD.bazel:22:11: no such package '@tflm_pip_deps_importlib_metadata//': The repository '@tflm_pip_deps_importlib_metadata' could not be resolved: Repository '@tflm_pip_deps_importlib_metadata' is not defined and referenced by '@tflm_pip_deps_markdown//:pkg'
ERROR: Analysis of target '//tensorflow/lite/micro/examples/hello_world:evaluate' failed; build aborted: 
INFO: Elapsed time: 1.697s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\igured)

**Comment by cdknorow** [comment]
Hi I was having this issue as well. If you use their docker image it will work however.

>> docker run -it -v <path-to-tflite-micro>:/tflite-micro  tflm-ci bash 
>> bazel run tensorflow/lite/micro/tools/gen_micro_mutable_op_resolver:generate_micro_mutable_op_resolver_from_model  --flags

  It looks like at some point they switched from python3.9 -> 3.10 and you are probably having some configuration issues on your host machine (I was).

**Comment by ruggedman** [comment]
Hi.
Thanks! I was able to run hello-world inside the docker image.

**Comment by fatsheep2020** [comment]
same issue on build hello-world

**Comment by Libianno** [comment]
> Hi I was having this issue as well. If you use their docker image it will work however.
> 
> > > docker run -it -v :/tflite-micro  tflm-ci bash
> > > bazel run tensorflow/lite/micro/tools/gen_micro_mutable_op_resolver:generate_micro_mutable_op_resolver_from_model  --flags
> 
> It looks like at some point they switched from python3.9 -> 3.10 in one of their requirement files and you are probably having some configuration issues on your host machine (I was).

Hello.
Where did you find this docker image?

**Comment by Libianno** [comment]
Problem in hello-world soved using a venv with ython3.11
