### ISSUE TITLE
Does tflite micro support pure C inference?

### ISSUE THREAD

**Issue by heetez1euler** [tensorflow/tflite-micro#1992]
I have search on web. Everyone and even tensorflow lite website mentions example where tflite inference is run using CPP or python etc. But not pure C. I want to run tflite model on arm cortex m4 while inference written in pure C.

Can anyone share possible C snippet and example how to use in C

**Comment by ScholliYT** [comment]
You might want to look at this project for pure C inference https://github.com/iml130/nncg
