### ISSUE TITLE
Failed to get registration from op code CUSTOM

### ISSUE THREAD

**Issue by fathiabdelmalek** [tensorflow/tflite-micro#2006]
I have a problem uploading my model to an `esp32`, I have a Keras model converted to `tflite` and then to `c array`, but the conversation to `tlite` model is simple without any additional flags, and I'm getting this error but without a solution
```
Failed to get registration from op code CUSTOM
```
Any solution for this problem, I really need a solution to complete my thesis project.
I have tried both tflite::AllOpsResolver and tflite::MicroMutableOpResolver.
My model is quite simple:
- input layer with shape (150, 11).
- lstm layer with 12 units.
- output layer with 14 units.

**Comment by SaketNer** [comment]
Hello, have you correctly initialised the UnidirectionalSequenceLSTM micromuctableopresolver. Unlike other op resolvers it seems to need an input. You could try checking that.
