### ISSUE TITLE
Microspeech Example on STM32-F401re

### ISSUE THREAD

**Issue by Elmaco7** [tensorflow/tflite-micro#2007]
Hi all, I don't know if this is the right place to ask this question. I'm trying to delpoy the microspeech example on an STM32-F401re Microcontroller, through the Mbed Studio IDE. To do this, I need to create the project, but I noticed that it is no longer possible to do it with the "make" command. 
Does anyone know how I could do?
Thanks to whoever will answer

**Comment by AbrahamLinc0ln** [comment]
I am working through a similar issue using the STM32H745I-DISCO. From my reading, you will want to look at this page: https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/new_platform_support.md
