### ISSUE TITLE
TFLite Micro : "SELECT" kernel : SelectPrepare() not deallocating temp tensors in node preparation.

### ISSUE THREAD

**Issue by simon6611** [tensorflow/tflite-micro#2010]
Hello, 
I am using the Select_V2 operation in a TF Micro framework and I believe that the method [`TfLiteStatus SelectPrepare(TfLiteContext* context, TfLiteNode* node)`](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/select.cc#L78)
is not working as intended.

I noticed that `TfLiteStatus MicroAllocator::FinishPrepareNodeAllocations(int node_id)` throws an error on the node of Select_V2. 
This stems from the allocator's
- `tflite::non_persistent_arena_buffer_allocator::temp_buffer_count_` not being 0
- `tflite::non_persistent_arena_buffer_allocator::temp_buffer_ptr_check_sum` not being 0

after the node preparation. 

After some debugging I believe that it is caused by anticipated return of that method mentionned above : 
`TfLiteStatus SelectPrepare(TfLiteContext* context, TfLiteNode* node)`. 

The method allocates temp tensors, perfoms a fraction of the checks and returns `kTfLiteOk` without performing the remaining checks and deallocating the temp tensors. 

I believe that the [following lines](https://github.com/tensorflow/tflite-micro/blob/9dc65ef8ae8c2ea38f56e3a74ccf4356f6a8df58/tensorflow/lite/micro/kernels/select.cc#L104)

```
if (GetTensorShape(input_condition).FlatSize() == 1 &&
      GetTensorShape(input_x).FlatSize() == 1 &&
      GetTensorShape(input_y).FlatSize() == 1 &&
      GetTensorShape(output).FlatSize() == 1) {
    return kTfLiteOk;
  }
```

should be changed to 
```
if ((GetTensorShape(input_condition).FlatSize() != 1) ||
      (GetTensorShape(input_x).FlatSize() != 1) ||
      (GetTensorShape(input_y).FlatSize() != 1) ||
      (GetTensorShape(output).FlatSize() != 1)) {
    return kTfLiteError;
  }
```
I have tested this edit on my own project and it seems to fix the issue. But I am a novice in C++ and in collaborative development so I can only open this issue... I hope someone can correct me or the code.
Thanks in advance!

**Comment by ddavis-2015** [comment]
Thank you for your interest in TFLM.  Your issue has been identified as a bug, and will be resolved with PR #2013.  When this PR is merged, your issue will automatically close.
