### ISSUE TITLE
Xtensa optimized kernels for AveragePool and MaxPool

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tflite-micro#205]
https://github.com/tensorflow/tflite-micro/pull/139 is adding Xtensa optimized implementations for AveragePool and MaxPool.

Prior to being able to merge the Xtensa implementations, we will need to refactor the reference implementation (and the CMSIS optimized implementation) to better share code and reduce the maintenance overhead.

This issu will track the work needed for such a refactoring as well as getting the Xtensa kernels merged.

**Comment by advaitjain** [comment]
Tagging @bhanuprakashbv @nyadla-sys @vp-cad @sjoshi768

**Comment by petewarden** [comment]
Closing, since the refactoring appears to be done.
