### ISSUE TITLE
VAR_HANDLE requires resource variables. Please create ResourceVariables and pass it to the interpreter.

### ISSUE THREAD

**Issue by Raise-me-up** [tensorflow/tflite-micro#2101]
As shown in the question, how to solve the problem? The problem occurs when the stateful of LSTM is set to true.

**Comment by yair-ehrenwald** [comment]
Haven't tried it with LSTM yet, but something like this works for me in other cases:

uint8_t var_arena[4096];
tflite::MicroAllocator *ma = tflite::MicroAllocator::Create(var_arena, 4096);
tflite::MicroResourceVariables *mrv = tflite::MicroResourceVariables::Create(ma, 20);

interpreter = new tflite::MicroInterpreter(model, micro_op_resolver, tensor_arena, kTensorArenaSize, mrv );

**Comment by Raise-me-up** [comment]
@yair-ehrenwald It also works for me, thank you very much!

**Comment by ctwillson** [comment]
@Raise-me-up Have u ever quant the stateful model?
