### ISSUE TITLE
please bring back magic_wand example

### ISSUE THREAD

**Issue by ivan2angelov** [tensorflow/tflite-micro#2157]
I understand the reasons provided in issue #1851 , however I find magic wand example rather useful since it demonstrates how to use accelerometer sensor data and train own gesture recognition.
When you removed the magic wand example bunch of tutorials including Google Colab tutorial for training own gesture stopped working due to missing links in Github.

At the same time you have bunch of examples on how to train speech models in the source. Acquiring speech requires microphone, while acceleration sensor is much more widely available (and cheap to integrate). Accelerometer sensor is much more common in MCU-based evaluation kits, and it is much more useful for learning how to use and train own ML models.

I am begging you, could you please bring back magic wand?

**Comment by ddavis-2015** [comment]
@ivan2angelov 

Thank you for your interest in TFLM.  The magic_wand example continues to live on in the [tflite-micro-arduino-examples](https://github.com/tensorflow/tflite-micro-arduino-examples/tree/main/examples/magic_wand) repository.  There you will find a Colab compatible training script (which I just now tested, and which works with no issues).

You will also find code for use with the Arduino Nano 33 BLE within the Arduino environment.  There is also a web app that allows you to generate and save your own gesture data (requires Chrome web browser, bluetooth connectivity and Arduino Nano 33 BLE).
