### ISSUE TITLE
Tuning a model on microcontroller 

### ISSUE THREAD

**Issue by Tabatabaei1999** [tensorflow/tflite-micro#2175]
hello, first thanks for your great work!
I have an embedded board that contains a microcontroller and some sensors. I find that only by using transfer learning we can solve this problem, which means that at first, we train the model on PC, then move this model to the microcontroller so for example every single week the unfreeze layer of the model is tuned with data obtain from sensors on the microcontroller. Can I implement this idea using Tensorflow-lite for microcontrollers?

**Comment by yair-ehrenwald** [comment]
How about recording data using the device and then using that data to train the model and later deploy using TFLM?

**Comment by Tabatabaei1999** [comment]
No, the project doesn't allow me to use this.
