### ISSUE TITLE
Can't compile binary for cortex-m4

### ISSUE THREAD

**Issue by jsmith173** [tensorflow/tflite-micro#2191]
### 1. System information
- OS Platform and Distribution: Ubuntu Linux 22
- TensorFlow : tflite-micro: from github

### 2. Problem
Trying to follow:
https://www.tensorflow.org/lite/microcontrollers/library

make -f tensorflow/lite/micro/tools/make/Makefile TARGET=cortex_m_generic TARGET_ARCH=cortex-m4 hello_world_bin

Error message:
fatal error: ARMCM4.h: No such file or directory

**Comment by mansnils** [comment]
Hi @jsmith173 ,

TARGET=cortex_m_generic is generic in the sense you can run any TARGET_ARCH=cortex-mXX. It means you can only build the microlite library. It is not bound to any specific platform. The user then provides needed startup/platform files for a given platform/app.

If you want to run the hello world example you could check out TARGET=cortex_m_corstone_300.

More info:
https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/cortex_m_generic
https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/cortex_m_corstone_300
