### ISSUE TITLE
About endian issue

### ISSUE THREAD

**Issue by liamsun2019** [tensorflow/tflite-micro#2209]
Hi Author,

I want to integrate a model basing on tflite micro APIs. The running platform is in big endian. My concern is if there's anything that needs to be handled specially as for endian issue? My model may be a floating one instead of int8. Thanks for your time.

**Comment by voldrfr1** [comment]
Hi, I faced a similar issue and found a dirty workaround, see [this link](https://discuss.tensorflow.org/t/running-tflite-micro-on-be-platform/14234/3). However, I don't recommend using it in production code.
