### ISSUE TITLE
When building firmware I get memmap.h: No such file or directory

### ISSUE THREAD

**Issue by MATTYGILO** [tensorflow/tflite-micro#2213]
I am getting this error when building on esp32s3

```
tflite-micro/tensorflow/lite/experimental/microfrontend/lib/frontend_memmap_main.c:17:10: fatal error: memmap.h: No such file or directory
 #include "memmap.h"
```

But, I cannot find memmap.h file anywhere.

All help would be much appreciated

**Comment by yair-ehrenwald** [comment]
Try building the version from:
https://github.com/espressif/tflite-micro-esp-examples/tree/master

Worked for me using the instructions @vikramdattu wrote :)
