### ISSUE TITLE
Cannot create an interpreter for the person detection model

### ISSUE THREAD

**Issue by uraich** [tensorflow/tflite-micro#2286]
When trying to create and tflm interpreter on the person detection model with
interpreter = tflite.Interpreter(model_path = "person_detection_int8/person_detect_model.tflite")
it fails saying:
ValueError: quantized_dimension must be in range [0, 1). Was 3.Tensor 33 has invalid quantization parameters.quantized_dimension must be in range [0, 1).

**Comment by avptin** [comment]
There are already a few similar issues reported here... have you looked at https://github.com/tensorflow/tensorflow/issues/41324#issuecomment-657508551?
