### ISSUE TITLE
Model Deployment in cortex M-7/M-4 Microcontroller Arduino Nicla Vision

### ISSUE THREAD

**Issue by atosh603** [tensorflow/tflite-micro#2302]
Hello team. I have trained one model based on our Custom Dataset, using tensor flow Object detection API. Then I converted it into TFLite model.
Then I used this XXD command line to generate .cc flat buffer for each model including int8 precision model. 
Now he challenge is how can I use this Tflm flatbuffer that is generated according to Tensor flow website, **How can I deploy this model in Cortex M series Microcontroller like Arduino Nicla Vision.**

Arduino Nicla Vision works with OpenMV IDE. How to deploy my model in my scenario?

Please reply As soon as possible.

**Comment by ddavis-2015** [comment]
@atosh603 

Hello and thank you for your interest in TFLM.  I am afraid that no support for the Nicla Vision board is available with regard to TFLM.  While this board is an Arduino product and compatible with the Arduino IDE, it appears the IDE is only used to update the board bootloader.  The Nicla Vision board appears to be primarily designed for use with MicroPython and the OpenMV MicroPython loadable library.  Instructions for using this can be found on the [Arduino website](https://docs.arduino.cc/tutorials/nicla-vision/getting-started?queryID=6b476a1e036402d5badbfaa66b9377b3).
