### ISSUE TITLE
Person Detection for Sparkfun Edge | No rule to make target

### ISSUE THREAD

**Issue by yepurivamsikrishna** [tensorflow/tflite-micro#2312]
I'm trying to build person detection example for running on sparkfun edge. But it gives the following error. I was using Ubuntu 22.04 OS.

yvk@test-vm:~/tflite-micro# **make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge micro_speech_bin**
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/kissfft already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
tensorflow/lite/micro/tools/make/Makefile:626: tensorflow/lite/micro/tools/make/targets/sparkfun_edge_makefile.inc: No such file or directory
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/targets/sparkfun_edge_makefile.inc'.  Stop

**Comment by h-tye** [comment]
@yepurivamsikrishna I have run into the same issue. Were you ever able to get around this?
