### ISSUE TITLE
run a new model

### ISSUE THREAD

**Issue by zrx563010758** [tensorflow/tflite-micro#2316]
I am running a new model that I trained through tensorflow lite using tflite  micro.
when I run the code:
`  // Allocate memory from the tensor_arena for the model's tensors.`
 ` TfLiteStatus allocate_status = interpreter->AllocateTensors();`
it returned:
`TfLiteStatus  = kTfLiteError`

but when I run the official model,it works well.
someone can help me ?

**Comment by zrx563010758** [comment]
this is my model:
[my_model.zip](https://github.com/tensorflow/tflite-micro/files/13362765/my_model.zip)

**Comment by zrx563010758** [comment]
this is the official code, when I run this code ,the program works well.
[Uploading person_detect.zip…]()

**Comment by Hyeongseon** [comment]
Did you solved?
