### ISSUE TITLE
src/third_party/cmsis_nn/Include/arm_nnsupportfunctions.h:847: undefined reference to `__sxtb16

### ISSUE THREAD

**Issue by Gostas** [tensorflow/tflite-micro#2331]
Hi,

I am building the tflite-micro-arduino-examples for the Nano 33 BLE. I have updated the source files to use the latest version from this repo and also updated to the examples (fork with updated scripts and examples https://github.com/Gostas/tflite-micro-arduino-examples).

I would get the following error for 'hello_world', which I fixed by substituting SXTB16 for __sxtb16:
```
/tmp/build/third_party/cmsis_nn/Source/NNSupportFunctions/objs.a(arm_nn_vec_mat_mult_t_s4.c.o): In function `read_and_pad_s4':
/home/tflite/src/third_party/cmsis_nn/Include/arm_nnsupportfunctions.h:847: undefined reference to `__sxtb16'
/home/tflite/src/third_party/cmsis_nn/Include/arm_nnsupportfunctions.h:848: undefined reference to `__sxtb16'

/tmp/build/third_party/cmsis_nn/Source/NNSupportFunctions/objs.a(arm_nn_vec_mat_mult_t_s4.c.o):
/home/tflite/src/third_party/cmsis_nn/Include/arm_nnsupportfunctions.h:848: more undefined references to `__sxtb16' follow
collect2: error: ld returned 1 exit status
```

This example would pass compilation, but in the next one, 'micro_speech', I get

```
/tmp/build/third_party/cmsis_nn/Source/ConvolutionFunctions/objs.a(arm_depthwise_conv_3x3_s8.c.o): In function `arm_depthwise_conv_3x3_s8':
/home/tflite/src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c:137: undefined reference to `__smlabb'
/home/tflite/src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c:139: undefined reference to `__smlatt'
(more occurences)
collect2: error: ld returned 1 exit status
```

Am I missing any files? Or is the Mbed CMSIS library missing some files?

I am using the arduino:mbed_nano 4.0.10 core and compiling with `-mcpu=cortex-m4 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 -mthumb`

Thanks

**Comment by Gostas** [comment]
I'm using the latest version of CMSIS_NN, so src/third_party/cmsis_nn/Include/Internal/arm_nn_compiler.h contains
```
// ACLE intrinsics under groups __ARM_FEATURE_QBIT, __ARM_FEATURE_DSP , __ARM_FEATURE_SAT, __ARM_FEATURE_SIMD32

// Note: Just __ARM_FEATURE_DSP is checked to collect all intrinsics from the above mentioned groups

#if (defined(__ARM_FEATURE_DSP) && (__ARM_FEATURE_DSP == 1))

    // Common intrinsics
    #define SMLABB __smlabb
    #define SMLATT __smlatt
    #define QADD __qadd
    #define QSUB8 __qsub8
    #define QSUB16 __qsub16
    #define SADD16 __sadd16

    // Compiler specifc variants of intrinsics. Create a new section or file for IAR if needed
    #if defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050) || defined(__ICCARM__)

        #define SMULBB __smulbb
        #define SMULTT __smultt
        #define ROR __ror
        #define SXTB16 __sxtb16
        #define SXTAB16 __sxtab16
        #define SXTB16_RORn(ARG1, ARG2) SXTB16(ROR(ARG1, ARG2))
        #define SXTAB16_RORn(ARG1, ARG2, ARG3) SXTAB16(ARG1, ROR(ARG2, ARG3))
        #define SMLAD __smlad

...

__STATIC_FORCEINLINE uint32_t SXTB16(uint32_t op1)
{
    uint32_t result;

    __ASM("sxtb16 %0, %1" : "=r"(result) : "r"(op1));
    return (result);
}
```
and src/third_party/cmsis_nn/Include/arm_nnsupportfunctions.h
```
#include "third_party/cmsis_nn/Include/Internal/arm_nn_compiler.h"
#include "third_party/cmsis_nn/Include/arm_nn_math_types.h"
#include "third_party/cmsis_nn/Include/arm_nn_types.h"
```

I try using the base arduino_examples files. If you want to reproduce, you can use the scripts in my repo linked above to create an arduino library. Most importantly, you need the MANIFEST.ini file, the updated source code for the hello_world example and to make sure the signal/ dir is moved under src/ in the library.

**Comment by ddavis-2015** [comment]
@Gostas @mansnils 

Just adding my two-cents here based on my hazy recollection of March 2023:

1. The downloaded version of CMSIS and CMSIS_NN changed after Feb. 27 2023
2. After Feb. 27 2023, the intrinsics that were defined in the CMSIS header files no longer included all intrinsics used by the arduino-example repo. code base.
3. The Arduino supplied compiler for the NRF52840 (Nano 33) does not supply these missing intrinsics.
4. The arduino-examples repo was frozen at this point.

Note: The arduino-examples repo. was frozen in a working state, such that the Nano 33 BLE compiles would succeed.

**Comment by Gostas** [comment]
Thanks for your response @ddavis-2015 .

I tried compiling with a newer compiler, gcc-arm-none-eabi-10.3-2021.10, but same results.

It looks like it's the same issue as https://github.com/tensorflow/tensorflow/issues/48741.

For now I'll just use the arduino-examples library as-is.

Appreciate your help guys.

**Comment by Gostas** [comment]
For reference, I was able to fix the error above by including in the Tflm library the version of CMSIS that comes along Mbed OS for the Arduino Mbed Nano boards (.arduino15/packages/arduino/hardware/mbed_nano/4.0.10/cores/arduino/mbed/cmsis/CMSIS_5) AND using gcc-arm-none-eabi-10.3-2021.10.

All the examples compile and work correctly, with minor modifications that reflect the updates in the library.

I've also included a modified version of the makefile and supporting files to generate a static Arduino library.

You can view my fork here: https://github.com/Gostas/tflite-micro-arduino-examples .

I guess there wouldn't be any interest in updating the Arduino library, since a newer version of the toolchain is needed?

**Comment by IzIzumi** [comment]
Hi Gostax,
For example, if you submit the build using the Arduino IDE, it works fine.
However, it still shows an error on Platformio. Can you help me fix this?
