### ISSUE TITLE
Cannot find create_sine_model.ipynb

### ISSUE THREAD

**Issue by gihyeonjeon** [tensorflow/tflite-micro#2374]
I heard that new directory of create_sine_model.ipynb is here:
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb

But I cannot find it. Is directory changed again? Where is the directory which is latest?

**Comment by JBernouli** [comment]
tensorflow/lite/micro/examples/hello_world/train.py this might be it?
