### ISSUE TITLE
 How do I add TFLM to the new Ti platform (Cortex-R5F) 

### ISSUE THREAD

**Issue by enting8696** [tensorflow/tflite-micro#2442]
First of all, thank you for the resources you provided. 
I am a researcher trying to use the single chip field for the first time.

After seeing many TensorFlow Lite official documents, a lot of information about Ti is that it only supports the Cortex-M series platform.

Now the hardware I am using is Ti AWR2944 with Cortex-R5F and I use CCS as IDE. How do I import TensorFlow Lite into my project?

**Comment by rascani** [comment]
You will need to port TFLM to this platform. I would suggest starting here: https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/new_platform_support.md

Once you implement the basic platform support, you should be fine to use TFLM with the portable reference kernels. Performance will probably not be good, but it will be functional.
