### ISSUE TITLE
Handwritten number recognition example

### ISSUE THREAD

**Issue by reymor** [tensorflow/tflite-micro#2452]
In September 2020, I did a small project with TFLM in STM32F429-DISC1, recently I test with CMSIS-NN and the improvement is quite interesting. I though if there is any interest in add it to Community Examples. I could improve more the documentation and the integration if it is needed

[model_running_cmsis-nn.webm](https://github.com/tensorflow/tflite-micro/assets/39070043/4247f92a-9707-45e8-9444-bd0d78ca7d8a)

https://github.com/reymor/stm32f429-tflite-micro-mnist

Thanks in advance,

**Comment by rascani** [comment]
This is really cool! Thank you for offering this. Let me think about how best to get it added and I'll follow up.
