### ISSUE TITLE
how to combine audio_preprocessor model and micro_speech into one tflite

### ISSUE THREAD

**Issue by kismeter** [tensorflow/tflite-micro#2463]
In Micro Speech sample using TensorFlow Lite Micro (TFLM) on two models for wake-word recognition. The first model is an audio preprocessor that generates spectrogram data from raw audio samples. The "audio_preprocessor_int8.tflite" generated by audio_preprocessor.py. The second is the Micro Speech model, a less than 20 kB model that can recognize 2 keywords, "yes" and "no", from speech data.  the model is micro_speech_quantized.tflite. is it possible to combine these two tflite models into one tflite model?

**Comment by ddavis-2015** [comment]
@kismeter 

If you are asking whether the `.tflite` files can be combined, the answer is no.  The `.tflite` files represent a converted version of the original TensorFlow models.  You can however use the experimental TensorFlow analyzer function to view the layers in the `.tflite` files, and you can load such files into the TensorFlow Lite interpreter and extract the weights in each layer.  In this way you could recreate any model.

If you want to combine the models within TensorFlow using Python, you could use Keras custom layers.  For audio preprocessing, instantiate the _GenerateFeature class and wrap it in a custom Keras layer.  For word recognition, you would use the train_micro_speech_model script, and load the `SAVED_MODEL` file.  You should be able to wrap the result in another keras custom layer.  Then just make your new unified model from the custom layers.

Good luck.

This issue will now be closed.  Please feel free to reopen the issue should you have additional comments.
