### ISSUE TITLE
Supporting Qualcomm Sensing Hub AI Accelerator?

### ISSUE THREAD

**Issue by xumengwei** [tensorflow/tflite-micro#2481]
I just read this [post](https://www.qualcomm.com/content/dam/qcomm-martech/dm-assets/documents/snapdragon_888_ai_blog_by_jeff_gehlhaar_vp_of_technology_hsin-i_hsu_senior_product_manager.pdf), which mentioned that there's a second AI accelerator on Qualcomm's Sensing Hub. It also said they were working to allow developers access to it through Tflite micro. I wonder if this has come true, or not? Thanks!

**Comment by pro9code** [comment]
Please answet

**Comment by rascani** [comment]
I would suggest checking with Qualcomm.

**Comment by pro9code** [comment]
FYI they won't let you, I asked.

**Comment by pro9code** [comment]
Scary
