### ISSUE TITLE
Origin of `micro_speech` `audio_preprocessor_test.py` `expected` var values?

### ISSUE THREAD

**Issue by gamename** [tensorflow/tflite-micro#2487]
Hi,

I'm walking through the process of creating my own models (for a cat meowing).  One thing I don't understand is the way `audio_preprocessor_test.py` works.  Specifically, how do you get the values used in the `expected` variables (below).  Is there some other pre-process I need to run to get them?

Thank you,
-T

```Python
  def testFeatureOutputYes(self):
    feature_params = audio_preprocessor.FeatureParams()
    audio_pp = audio_preprocessor.AudioPreprocessor(feature_params)
    audio_pp.load_samples(Path(self.sample_prefix_path, 'yes_30ms.wav'))
    feature = audio_pp.generate_feature_using_tflm(audio_pp.samples)
    feature_list = feature.numpy().tolist()
    expected = [
        124, 105, 126, 103, 125, 101, 123, 100, 116, 98, 115, 97, 113, 90, 91,
        82, 104, 96, 117, 97, 121, 103, 126, 101, 125, 104, 126, 104, 125, 101,
        116, 90, 81, 74, 80, 71, 83, 76, 82, 71
    ]
    self.assertSequenceEqual(feature_list, expected)

  def testFeatureOutputNo(self):
    feature_params = audio_preprocessor.FeatureParams()
    audio_pp = audio_preprocessor.AudioPreprocessor(feature_params)
    audio_pp.load_samples(Path(self.sample_prefix_path, 'no_30ms.wav'))
    feature = audio_pp.generate_feature_using_tflm(audio_pp.samples)
    feature_list = feature.numpy().tolist()
    expected = [
        126, 103, 124, 102, 124, 102, 123, 100, 118, 97, 118, 100, 118, 98,
        121, 100, 121, 98, 117, 91, 96, 74, 54, 87, 100, 87, 109, 92, 91, 80,
        64, 55, 83, 74, 74, 78, 114, 95, 101, 81
    ]
    self.assertSequenceEqual(feature_list, expected)


```

**Comment by ddavis-2015** [comment]
@gamename 

The `audio_preprocessor_test.py` serves as a smoke test for the operators that the audio preprocessor uses.  The `expected` values were generated by feeding the audio preprocessor model and sample data to either TensorFlow or the TfLite interpreter (I don't remember which one I used).

An example of using the TfLite interpreter is available in the `hello_world` example `evaluate` scripts.

For the TFLM signal operator plugins to be available to TensorFlow/TfLite, you must use Bazel to build/run your python scripts.
