### ISSUE TITLE
Optimizing the memory usage of a model

### ISSUE THREAD

**Issue by rudolflovrencic** [tensorflow/tflite-micro#2513]
Greetings!

I have a simple CNN model that is `318.39KB` in size:
```python
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(125, 90, 1)),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(4,4)),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(4,4)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(3),
    tf.keras.layers.Softmax(),
])
```

The `tflite::RecordingMicroInterpreter` reports: `[RecordingMicroAllocator] Arena allocation total 1472624 bytes` which is about `1.4MB`.

I've read [this blog](https://blog.tensorflow.org/2020/10/optimizing-tensorflow-lite-runtime.html) and [tflite-micro memory management docs](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/memory_management.md) and as far as I understand, the `1.4MB` is allocated because of intermediate tensors. Since [the docs](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/memory_management.md#head-section) say that `tflite::GreedyMemoryPlanner` is already utilized for the head section which makes up the most of the `1.4MB`, I assume my model is a poor fit for that planner.

Should I (and how to) change the model to cater the planner so that buffers for intermediate tensors are able to be reused? Is there another approach to reduce memory usage?

**Comment by rascani** [comment]
As you probably read, the `GreedyMemoryPlanner` tries to re-use arena space once it knows an intermediate tensor is no longer in use. One debug utility that is sometimes useful is an ASCII art visualization of the memory plan. That can be accessed using this API: https://github.com/tensorflow/tflite-micro/blob/cf0a5609a834895695250518a2a0ac8525e96ccf/tensorflow/lite/micro/memory_planner/greedy_memory_planner.h#L86. 

I would also suggest using a model visualization tool like Netron to see the trace of tensors through the TFLite graph. Look for tensors that have to be preserved for a large number of layers. Those are the ones I would try to target for restructuring to reduce the memory footprint. You can also look at quantization (if you haven't already), which can reduce both the model and arena size.
