### ISSUE TITLE
The difference between tensorflow lite and tensorflow lite micro

### ISSUE THREAD

**Issue by ctwillson** [tensorflow/tflite-micro#2524]
I read the doc about the operators difference between TensorFlow Lite and  TensorFlow 
![image](https://github.com/tensorflow/tflite-micro/assets/16146306/4c7804d6-d395-4ba9-b078-b51e9365e6a6)
However,but I have no idea about the difference between TensorFlow Lite and  TensorFlow Lite micro

**Comment by rascani** [comment]
The difference between TensorFlow Lite and TensorFlow Lite for Microcontrollers is the platforms they target. TFLite is targeted at mobile use cases, such as Android & iOS devices. As the name suggests, TFLite-Micro is aimed at low-power microcontrollers and digital signal processors for embedded use cases. These can even be baremetal use cases, as TFLM has no dependencies on an operating system.

**Comment by ctwillson** [comment]
> The difference between TensorFlow Lite and TensorFlow Lite for Microcontrollers is the platforms they target. TFLite is targeted at mobile use cases, such as Android & iOS devices. As the name suggests, TFLite-Micro is aimed at low-power microcontrollers and digital signal processors for embedded use cases. These can even be baremetal use cases, as TFLM has no dependencies on an operating system.

Are the operators supported by TF lite same as TF Microcontrollers?In other words,if I have .tflite,I used cmd like "xxd -i converted_model.tflite > model_data.cc" and the microcontrollers have enough memories,so it must can be loaded normally?

**Comment by rascani** [comment]
TFLM supports the same .tflite model format as TFLite. However, there are some operators that are unimplemented. For the most part, these can be ported from TFLite as needed and there is a [guide](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/porting_reference_ops.md) on how to do so.
