### ISSUE TITLE
How to add OpenCV to build successfully person detection project?

### ISSUE THREAD

**Issue by huytranvan2010** [tensorflow/tflite-micro#2559]
I follow this project and can run test https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/person_detection#run-the-tests-on-a-development-machine. But now I want to evaluate Tflite C array model in TFLM. So that I need OpenCV to read all images, resize images and run inference. I installed OpenCV in my PC. How can I add OpenCV to build successfully person detection project? I mean that how can I add OpenCv to makefile to build this project. Generally, for OpenCV project, I can use this guide https://docs.opencv.org/4.x/db/df5/tutorial_linux_gcc_cmake.html to build project with OpenCV via cmake. But with TFLM, I dont know to do it.

Thank you.

**Comment by ddavis-2015** [comment]
@huytranvan2010 

The following repository has an example of using TFLM with CMake builds for the Raspberry Pi Pico microcontroller:

https://github.com/raspberrypi/pico-tflmicro

That repo. is not part of Google or TFLM and no Google support can be provided with regards to the use of that repo.

This issue will now be closed.  Please feel free to reopen the issue should you have additional comments.
