### ISSUE TITLE
How to run the the program main.cc in the person detection project?

### ISSUE THREAD

**Issue by aidevmin** [tensorflow/tflite-micro#2561]
I could run test for the project in my PC https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/person_detection but I do not see any guide to run the main program main.cc via make file in the PC. Please add this guide. I need it to evaluate tflite C array in PC.
Thank you so much.

**Comment by ddavis-2015** [comment]
@aidevmin 

The additional make targets for the person_detection example are as follows:
```
make -f tensorflow/lite/micro/tools/make/Makefile person_detection
make -f tensorflow/lite/micro/tools/make/Makefile person_detection_bin
make -f tensorflow/lite/micro/tools/make/Makefile run_person_detection
```

The last of these should continuously output: 
`person score:-72 no person score 72`

[internal note: documentation update]
