### ISSUE TITLE
Find LSTMCell accum_shift and LSTMCell accum_multiplier

### ISSUE THREAD

**Issue by Kullka** [tensorflow/tflite-micro#2575]
Hello everyone,
I'm trying to implement LSTM network after quantization by TensorFlow Lite to FPGA. But I don't know how to get LSTMCell **accum_shift** and LSTMCell **accum_multiplier**. Can anyone help me? Thank you. 

3 lines below can be found in https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/kernels/internal/reference/lstm_cell.h_
![image](https://github.com/tensorflow/tflite-micro/assets/93808532/f2376f18-333f-4a2f-9a07-34ed5461a0d1)

**Comment by ddavis-2015** [comment]
@Kullka 

The `LstmCell` method is only used with the legacy `LSTM` kernel operator, which TFLM does not support.  TFLM supports the `UNIDIRECTIONAL_SEQUENCE_LSTM` operator, which does not use the `LstmCell` method.  The legacy `LSTM` operator is still supported in the [TensorFlow repository](https://github.com/tensorflow/tensorflow/tree/master).  Any additional questions regarding `LSTM` should be posted as an issue in that repository.

The `accum_shift` and `accum_multiplier` are computed using `tflite::QuantizeMultiplier` and the code for these values can be found [here](https://github.com/tensorflow/tensorflow/blob/e33a5ea470d1ef02107b595737d23670f7a1eda4/tensorflow/lite/kernels/lstm.cc#L2326).
