### ISSUE TITLE
can not access https://source.codeaurora.org/quic/embedded_ai/tensorflow

### ISSUE THREAD

**Issue by peyer** [tensorflow/tflite-micro#2596]
I just could not access https://source.codeaurora.org/quic/embedded_ai/tensorflow, will you sync to github?

**Comment by rascani** [comment]
We sync the small amount of tensorflow code to the tflite-micro repo that is needed for building, nothing more.

**Comment by peyer** [comment]
I am sorry to bother, but I could not find implementation code of HexagonEvalQuantizedInt8, will you tell me?

**Comment by rascani** [comment]
The Hexagon implementations are available in the Qualcomm Hexagon SDK
