### ISSUE TITLE
Want to check the variable values of OPs

### ISSUE THREAD

**Issue by haoliu001** [tensorflow/tflite-micro#2597]
Hi,

Recently, I wanted to check the values of some variables in OPs, like some variables inside the "inline void  FullyConnected(...)" function in the "fully_connected.h" file. 

To achieve it, I used the serial port to print it out after uploading the corresponding code.  It did not work. Do you have any suggestions for checking these values? (I did not use debugger since my MCUs do not support it well.)

Thanks in advance.

**Comment by ddavis-2015** [comment]
@haoliu001 

There are a few suggestions and tips I can offer:

1. Use `MicroPrintf` or `VMicroPrintf` from the `tensorflow/lite/micro/micro_log.h` file, for all of your debug output
2. Do not use the `ErrorReporter` class, as that has been deprecated
3. Did you have `BUILD_TYPE=release` as part of your `make` command?  If so, all debug output (and associated strings) will be removed from your application.  Use `BUILD_TYPE=` (empty) or `BUILD_TYPE=debug` as part of your `make` command.  The various build types can be found [here](https://github.com/ddavis-2015/tflite-micro/blob/8e22946b3faa51564df5dd9194f7540b2694892c/tensorflow/lite/micro/tools/make/Makefile#L213).
4. Did your application call `tflite::InitializeTarget()`?  Calling this method is required for all applications.  For some platforms, UART initialization occurs here.
5. If you are targeting a platform not supported by the TFLM repository, did you implement the target platform methods within `system_setup.cc` and `debug_log.cc`?  In particular, the methods in the `tensorflow/lite/micro/debug_log.h` file must be implemented for your platform.

This issue will now be closed.  Should you wish to add additional comments to this issue, please feel free to reopen the issue.
