### ISSUE TITLE
Building tflm lib for hexagon

### ISSUE THREAD

**Issue by sharvin-vittappan** [tensorflow/tflite-micro#2599]
Hi,

I am trying to build tflm lib for hexagon.
make command issued: 
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=hexagon OPTIMIZED_KERNEL_DIR=hexagon microlite

Error observed: tensorflow/lite/micro/tools/make/targets/hexagon_makefile.inc:42: *** HEXAGON_TFLM_LIB is undefined.  Stop.

How could I resolve this error?

Thanks

**Comment by rascani** [comment]
Hexagon support requires an additional library that is distributed as part of the Qualcomm Hexagon SDK.

**Comment by sharvin-vittappan** [comment]
Thank you @rascani . 
Even if I have additional library from Qualcomm and define HEXAGON_TFLM_LIB,
I am getting an error saying 

****_tensorflow/lite/micro/tools/make/Makefile:653: *** Incorrect OPTIMIZED_KERNEL_DIR: The optimized kernel directory: tensorflow/lite/micro/kernels/hexagon does not exist..  Stop._****
