### ISSUE TITLE
Support for rolled LSTM

### ISSUE THREAD

**Issue by zixiaoli0206** [tensorflow/tflite-micro#2600]
Dear contributors,

I am trying to deploy a LSTM-based network on STM32. However, I noticed that the deployment is only successful when I used unrolled LSTM. When I use the rolled LSTM, the Allocator always complains "failed to get the registration from op code CUSTOM". Is it true the framework cannot support rolled LSTM up to now? The unrolled LSTM taks much more storage than rolled LSTM.

**Comment by rascani** [comment]
From your description, I do not know what type of LSTM you're trying to deploy, but currently, the only LSTM we support is a unidirectional sequence LSTM.
