### ISSUE TITLE
Building tflm lib for hexagon 

### ISSUE THREAD

**Issue by sharvin-vittappan** [tensorflow/tflite-micro#2606]
Hi,
I am trying to build tflm lib for hexagon.
make command issued:
export HEXAGON_TOOL_VER=8.5.08
export HEXAGON_ROOT=/location of hexagon SDK/Hexagon_SDK/4.5.0.4/tools/HEXAGON_Tools
export HEXAGON_CPU_VER=v66
export HEXAGON_TFLM_LIB=/path to library/hexagon_tflm_core.a
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=hexagon OPTIMIZED_KERNEL_DIR=hexagon microlite

I get an error as:
tensorflow/lite/micro/tools/make/Makefile:653: *** Incorrect OPTIMIZED_KERNEL_DIR: The optimized kernel directory: tensorflow/lite/micro/kernels/hexagon does not exist..  Stop.

Related issue:https://github.com/tensorflow/tflite-micro/issues/2599

**Comment by ddavis-2015** [comment]
@sharvin-vittappan 

You will want to add `OPTIMIZED_KERNEL_DIR_PREFIX=${TENSORFLOW_ROOT}third_party` to your build command.  Examples of build commands for the Hexagon target can be found [here](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/ci_build/test_hexagon.sh).
