### ISSUE TITLE
generate project

### ISSUE THREAD

**Issue by abcd123abcd** [tensorflow/tflite-micro#2607]
Hi，
I follow thhe command:     make -f tensorflow/lite/micro/tools/make/Makefile generate_projects

But somthing went wrong :    make: *** No rule to make target 'generate_projects'.  Stop.

How can I generate KEIL project

**Comment by zinnourlahcene** [comment]
Hi. Did you find a solution for this issue. I'm trying to generate the code for the micro speech example, but I can't get it to work.
