### ISSUE TITLE
How to free a model after using tflite::GetModel

### ISSUE THREAD

**Issue by magnethead117** [tensorflow/tflite-micro#2617]
Hi,
I am using tflite::GetModel to get a model, however, when in the deinit process, I have no clue how to free the Model after using

`const tflite::Model* model_im = nullptr;
model_im = tflite::GetModel(my_model_data);`

I would be grateful for your response at your earliest convenience. Thanks.

**Comment by ddavis-2015** [comment]
TFLM does not use libc or libc++ memory allocation.  All dynamic memory allocation is done within the `arena` which is passed as a parameter to the instantiation of `MicroInterpreter`.  The `Model` and `MicroMutableOpResolver` are merely static data structures and also use no memory allocation methods.  Therefore the `MicroInterpreter`, `Model` and `MicroOpResolver` need not deallocate any memory once the application has complete all inference operations.
