### ISSUE TITLE
Feature request: Update Ethos-U driver ?

### ISSUE THREAD

**Issue by iabdalkader** [tensorflow/tflite-micro#2619]
Hi! It seems that the Ethos-U core driver currently used by tflite-micro is somewhat outdated. It's missing the `ethosu_address_remap` callback, which was introduced around release v23.02 (the current release is 24.05). This function is crucial; without it, invocation will fail if the NPU core cannot use addresses directly. 

Additionally, could you please consider allowing configuration arguments (such as the ones defined in `src/ethosu_config_uxx.h`) to be passed to the driver from the command line when building the library?

Thanks!

**Comment by rascani** [comment]
@mansnils

**Comment by mansnils** [comment]
Hi @iabdalkader 
Thanks for your interest in this. We shall update this example. Also keep in mind that contributions are welcome.

**Comment by iabdalkader** [comment]
https://github.com/tensorflow/tflite-micro/pull/2626
