### ISSUE TITLE
TFLM implementation in Contiki-NG

### ISSUE THREAD

**Issue by Muhammad-Haqdad** [tensorflow/tflite-micro#2663]
I want to implement TFLM in contiki-NG cooja simulator. how can i implement it need a help and guidance.

**Comment by rascani** [comment]
I'm not exactly sure what that is, but if you're interested in getting TFLM working on a new platform, please take a look at the docs located here: https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/new_platform_support.md
