### ISSUE TITLE
AllocateTensors() breaks on raspberry pi pico w

### ISSUE THREAD

**Issue by Zlisch** [tensorflow/tflite-micro#2686]
The original issue on TensorFlow repo is [here](https://github.com/tensorflow/tensorflow/issues/75831), which contains platform info, program source, and logs. I have tried with a much reduced [model](https://github.com/Zlisch/tflite-pico/blob/main/examples/impsy_model/musicMDRNN-dim4-layers1-units4-mixtures5-scale10.cc) (model size 13092B, # parameters = 369) but my basic prediction program still doesn't work.

Is there a way to decide how many `kTensorArenaSize` are needed before calling `AllocateTensors()`? Cause `interpreter->AllocateTensors()` always breaks my program and I cannot see any serial outputs.

**Comment by ddavis-2015** [comment]
@Zlisch 

From your post in the TensorFlow/TFLite repository, I do not see a properly formed application.  Missing is the assignment of the input TfLiteTensor and output TfLiteTensor, and a call to MicroInterpreter::Invoke.  I suggest looking at this example application which shows how to use the MicroInterpreter of TFLM: [hello world](https://github.com/tensorflow/tflite-micro-arduino-examples/blob/main/examples/hello_world/hello_world.ino)

Also, the call to tflite::InitializeTarget should only be made once, and must be called before attempting any output.  The tflite::InitializeTarget method participates in setting up serial output.  I would also use only MicroPrintf (from micro_log.h) within the application, as this is setup to be the most compatible with the target platform.

As for your question on arena size, there is the Generic Benchmark application, which can tell you how much arena space TFLM uses for your model (however you should probably make your arena just a small amount larger).  Documentation on how to run the benchmark is [here](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/tools/benchmarking) and the Cortex-M Corstone example should work for your Cortex-M0 device (RPi Pico).
