### ISSUE TITLE
Missing files when calling python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py

### ISSUE THREAD

**Issue by thomaspj101796** [tensorflow/tflite-micro#2688]
The built tree does not include the files tensorflow/lite/array.h and tensorflow/array.cc. I had to manually copy those files into the tree directory.

**Comment by rascani** [comment]
These files aren't actually necessary for TFLM. They are referenced in some common files with LiteRT, so they have to be present (else bazel complains). The only inclusion of array.h is actually conditional on `TF_LITE_STATIC_MEMORY`, which is likely the cause of your issue. Please make sure you're defining that, as it is essentially the TFLM conditional for common code between TFLM & LiteRT.

https://github.com/tensorflow/tflite-micro/blob/ce26927e22d976f8c363bd942f489c6900041833/tensorflow/lite/kernels/kernel_util.cc#L25-L29
