### ISSUE TITLE
How to preserve just some tensors?

### ISSUE THREAD

**Issue by andresovela** [tensorflow/tflite-micro#2764]
I have a model which requires some state handling, i.e. the model has several inputs and outputs, and some outputs need to be fed back into the inputs on the next invocation. This state feedback is a simple `memcpy(input, output, size)`.

Here's the problem, by the time the invocation has finished, the allocator has reused some of the tensors, so by the time I get to do the memcpy, the output tensors have garbage data.

I was able to make this work by creating the `MicroInterpreter` with the `preserve_all_tensors` flag set to true. This makes it so that the outputs are always valid. The problem is that this is a massive waste of memory; I only need to preserve a few tensors.

Is there a way to preserve just some tensors rather than all of them? If there isn't, how would I need to go about it? I'll gladly put up a PR to support this use case.

**Comment by ddavis-2015** [comment]
@andresovela 

This sounds like a good use of a resource variable (resource tensor) being added to your model (VAR_HANDLE, ASSIGN_VARIABLE, READ_VARIABLE).
