### ISSUE TITLE
quantize.cpp:58 input->type == kTfLiteFloat32 || input->type == kTfLiteInt16 || inp was not true

### ISSUE THREAD

**Issue by AdamMiltonBarker** [tensorflow/tflite-micro#280]
**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- Tensorflow version (commit SHA if source): 2.5.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arduino Nano 33 BLE Sense

**Describe the problem**

I have converted our CNN to TFLite using full integer quantization (in and out: uint8)
AllocateTensors fails with quantize.cpp:58 input->type == kTfLiteFloat32 || input->type == kTfLiteInt16 || inp was not true

![all_nano_33_ble_sense](https://user-images.githubusercontent.com/6291410/125519397-d10a8aa4-e1c9-4631-b896-a4f59b23aeee.png)

**Comment by advaitjain** [comment]
TFLM no longer supports the deprecated uint8 quantization (https://github.com/tensorflow/tflite-micro/issues/216). Our recommendation is to use int8 quantization.

**Comment by AdamMiltonBarker** [comment]
Ok your documentation really needs updating, all Github links are dead and there is no mention of this in this in the docs. Thanks for letting me know.
