### ISSUE TITLE
Stream method for loading the model from FlatBuffer (model.cc file)

### ISSUE THREAD

**Issue by NatakuG** [tensorflow/tflite-micro#285]
Hi, 

I would like to know whether there's a method to **stream the load from buffer**.

Since the model.cc file that generated only contains a buffer. 
e.g.:

        unsigned char converted_model_tflite[] = {
          0x18, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33, 0x00, 0x00, 0x0e, 0x00,
          // <Lines omitted>
        };
        unsigned int converted_model_tflite_len = 18200;

So I am trying to use **external files** which contains the same information instead of using a .cc file. Is there any method that I can use to **stream** the buffer when I load and use the model ?

For example, the method to load the model from .cc file is:

        model = tflite::GetModel(model_tflite);

The whole buffer takes quite a lot of space, and it will be quite a waste of space since I only invoke the model when it is needed.

**Comment by advaitjain** [comment]
Any optimizations to load a model into memory only when needed is outside the scope of the TFLM inference engine. Such optimizations will be closely tied to the broader application and should be implemented outside of TFLM.
