### ISSUE TITLE
Failed to get registration from op code AVERAGE_POOL_2D

### ISSUE THREAD

**Issue by stanleycelestin1** [tensorflow/tflite-micro#302]
Getting this error when running binary on stm32f746 board on serial bus:

```
Didn't find op for builtin opcode 'AVERAGE_POOL_2D' version '2'. 
An older version of this builtin might be supported. 
Are you using an old TFLite binary with a newer model?

Failed to get registration from op code AVERAGE_POOL_2D
```

Im sure the average pool 2d is part of the supported operations. What could be causing this? How would I remedy the issue?

**Comment by advaitjain** [comment]
If you are using the MicroMutableOpsResolver, you will need to explicitly call AddAveragePool2D.

https://github.com/tensorflow/tflite-micro/blob/45c80c969820fc96257f79ac197b6391dbbef741/tensorflow/lite/micro/micro_mutable_op_resolver.h#L142-L145

See keyword_benchmark as an example https://github.com/tensorflow/tflite-micro/blob/45c80c969820fc96257f79ac197b6391dbbef741/tensorflow/lite/micro/benchmarks/keyword_benchmark.cc#L54-L58

**Comment by stanleycelestin1** [comment]
Thanks @advaitjain! I actually had that in my code but my actual issue was that I allocated 5 operations in ` static tflite::MicroMutableOpResolver<5> micro_op_resolver;` but added 7 operations. The last two added operations didn't get captured. Once I changed to `<7>` I no longer have the issue. Thanks for the swift response.
