### ISSUE TITLE
Makefile is broken?

### ISSUE THREAD

**Issue by vikramdattu** [tensorflow/tflite-micro#361]
The new Makefile for generating example now picks all the sources instead of nit-picking.

Following lines seem to be culprit:

```
MICROLITE_CC_BASE_SRCS := \
$(wildcard tensorflow/lite/micro/*.cc) \
$(wildcard tensorflow/lite/micro/memory_planner/*.cc) \
$(TFL_CC_SRCS)

...

MICROLITE_CC_SRCS := $(filter-out $(MICROLITE_TEST_SRCS), $(MICROLITE_CC_BASE_SRCS))
MICROLITE_CC_SRCS := $(filter-out $(MICROLITE_BENCHMARK_SRCS), $(MICROLITE_CC_SRCS))
```

This generates wrong examples, e.g., in case of `esp`, all of these files get added to CMakeList and hence generated example fails to compile.

**Comment by njeffrie** [comment]
Should be fixed with https://github.com/tensorflow/tflite-micro/issues/361
