### ISSUE TITLE
KISS_FFT_TMP_ALLOC macro returns null but is used to write to memory

### ISSUE THREAD

**Issue by embeddetech** [tensorflow/tflite-micro#368]
I am working through compiler warnings for TFLM in Visual Studio, most of which are benign, but I came across one which appears to be legitimate.

In kiss_fft.c, there's a line in the kf_bfly_generic function:

`kiss_fft_cpx * scratch = (kiss_fft_cpx*)KISS_FFT_TMP_ALLOC(sizeof(kiss_fft_cpx)*p);`

This pointer is then later used to store a complex number:

`scratch[q1] = Fout[ k  ];`

However, the scratch variable pointer evaluates to zero, from this #define:

```
#define  KISS_FFT_TMP_ALLOC(nbytes) KISS_FFT_MALLOC(nbytes)
#define  KISS_FFT_TMP_FREE(ptr) KISS_FFT_FREE(ptr)
```

... which evaluates to zero:

```
#ifdef USE_SIMD
# include <xmmintrin.h>
# define kiss_fft_scalar __m128
#define KISS_FFT_MALLOC(nbytes) _mm_malloc(nbytes,16)
#define KISS_FFT_FREE _mm_free
#else	
#define KISS_FFT_MALLOC(X) (void*)(0) /* Patched. */
#define KISS_FFT_FREE(X) /* Patched. */
#endif	
```

I tried commenting that function out, but linker errors ensued. Is this not a problem with this library? How does this not cause erratic memory corruption?

**Comment by njeffrie** [comment]
I suspect this would be an issue if we used this method, but I grepped for it and we don't seem to use it anywhere in TFLM. 

We are currently only using kissfft in tensorflow/lite/experimental/microfrontend, which we hope to deprecate. Thank you for spotting this error, but I am hesitant to dedicate too much effort to fixing this unless we run into a correctness issue for one of our examples, or a user.
