### ISSUE TITLE
Building hello_world_test with TARGET=cortex_m_corstone_300 and TOOLCHAIN=armclang fails

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tflite-micro#390]
Trying to compile with the following command:
```
$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=cortex_m_corstone_300 TARGET_ARCH=cortex-m55 TOOLCHAIN=armclang hello_world_test
```

results in the following error:
```
armlink -o tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300_cortex-m55_default/bin/hello_world_test --stdlib=libc++ tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300_cortex-m55_default/obj/core/tensorflow/lite/micro/examples/hello_world/hello_world_test.o tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300_cortex-m55_default/obj/core/tensorflow/lite/micro/examples/hello_world/model.o tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300_cortex-m55_default/lib/libtensorflow-microlite.a --cpu=8.1-M.Main.mve.fp --strict --summary_stderr --info summarysizes --map --load_addr_map_info --xref --callgraph --symbols --info sizes --info totals --info unused --info veneers --list=tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300.map --entry=Reset_Handler --scatter=/path/to/tflite-micro/tensorflow/lite/micro/tools/make/downloads/ethos_u_core_platform/targets/corstone-300/platform.scatter /libtensorflow-microlite.a(startup_ARMCM55.o)
Fatal error: L6002U: Could not open file /libtensorflow-microlite.a: No such file or directory
Not enough information to list image symbols.
Not enough information to list load addresses in the image map.
Finished: 2 information, 0 warning, 0 error and 1 fatal error messages.
armclang: error: linker command failed with exit code 1 (use -v to see invocation)
tensorflow/lite/micro/examples/hello_world/Makefile.inc:35: recipe for target 'tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300_cortex-m55_default/bin/hello_world_test' failed
make: *** [tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300_cortex-m55_default/bin/hello_world_test] Error 1

```

From what I can see, it is caused by  the LIBDIR-variable in the [corstone_300 makefile](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc#L117) being empty, and thus the path to the microlite-lib becomes **/libtensorflow-microlite.a** instead of the expected **tensorflow/lite/micro/tools/make/gen/cortex_m_corstone_300_cortex-m55_default/lib/libtensorflow-microlite.a**.

The reason for LIBDIR being empty seems to be because, in the Makefile, [LIBDIR is being initialized](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/make/Makefile#L564
) after the [target makefile is included](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/make/Makefile#L620 
).

That change was introduced by the commit abb5e1546695373d8e1d2a34ae14747dd4b446d3, and moving the variable initialization back to its previous place (as in 2213e80afd3dfefea054fd429e55d1d1d46b81b2) seemingly fixes the issue, but I assume that it was moved to fix the ARC project generation, so that solution might create more problems than it solves.

**Comment by rockyrhodes** [comment]
I can compile with that same command minus the TOOLCHAIN=... argument with the current code base.  I don't have armclang installed, so was unable to execute exactly as shown.  Any reason this would work differently with the alternative toolchain?

**Comment by jenselofsson** [comment]
> I can compile with that same command minus the TOOLCHAIN=... argument with the current code base. I don't have armclang installed, so was unable to execute exactly as shown. Any reason this would work differently with the alternative toolchain?

I get the same thing, if I omit the TOOLCHAIN= argument, it works. Only the armclang if-clause uses LIBDIR, so that's why it works for gcc.
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc#L135

**Comment by advaitjain** [comment]
Apologies for the delay here.

Note that makefile based project generation beyond just ARC have been affected: https://github.com/tensorflow/tflite-micro/pull/360

Since we are going to be removing support for Makefile based project generation in the near future (https://github.com/tensorflow/tensorflow/issues/47413 and https://github.com/tensorflow/tflite-micro/issues/407), my preference here would be to modify tools/make/Makefile such that it works with armclang and then make any arc-specific fixes to ext_libs/arc_mli.inc

My guess here is that we should move GENDIR, LIBDIR etc to the top of the makefile (as before) and have @gerbauz and @vikramdattu provide `TARGET_ARCH=<blah>` as an explicit command line parameter to the Makefile in the short term. @gerbauz, @vikramdattu will that work?

@jenselofsson, it might be worth discussing how to add armclan to the CI so that we can catch such errors earlier.

**Comment by mansnils** [comment]
@advaitjain  Sounds good with having CI for Armclang, let's discuss that.. Meanwhile I provide a fix for Armclang, where GENDIR is moved up where it used to be. If that will not work for you, @vikramdattu  @gerbauz  (having an explicit command line parameter) we will have to think of something else.

**Comment by gerbauz** [comment]
Hi Advait,

Unfortunately, I’m on vacation now.
Can you please also ping @dzakhar?

Regards,
Artem Tsvetkov

**Comment by advaitjain** [comment]
@vikramdattu @dzakhar moving the variables to the top of the makefile (before including the target makefiles) was also required for https://github.com/tensorflow/tflite-micro/pull/432 and has been merged.

This does mean that the existing project generation for ESP and ARC would likely be broken again. I'm going to close this bug but please open a new one in case specifying `TARGET_ARCH` on the command line is insufficient.
