### ISSUE TITLE
Reshape ops is raised an error "num_input_elements != num_output_elements" (50 != 1)

### ISSUE THREAD

**Issue by colynhn** [tensorflow/tflite-micro#400]
When I replace my own model to the hello world model，the reshape ops is raised an error "num_input_elements != num_output_elements" (50 != 1) when input is a 2D tensor and output is a 1D tensor.

`reshape input: int32[1,50]`
`reshape output: int32[1]`
`reshape shape value = -1`

 But when I trace to the code: `tensorflow/lite/micro/kernels/reshape.cc: 56 int value = output_shape->data[i];` the value is always 1

So how can i fix this? thanks.
<img width="252" alt="1" src="https://user-images.githubusercontent.com/27861805/129319905-fa5f2161-7d8e-4411-8c4b-2a161d0b9b91.png">
<img width="482" alt="2" src="https://user-images.githubusercontent.com/27861805/129319919-d564fbe6-aab3-4096-b716-8e75e2a5237f.png">

**Comment by resorcap** [comment]
I met this problem too.

**Comment by petewarden** [comment]
Can you share a complete script you're using to create the model?

**Comment by petewarden** [comment]
Closing for now since there's been no update in a while. Please do reopen if you have more information available.
