### ISSUE TITLE
Hello World model array is generated unaligned

### ISSUE THREAD

**Issue by schneider42** [tensorflow/tflite-micro#418]
With #397 the hello world model cc and header gets generated using `tools/generate_cc_arrays.py`.

The script does not add an `alignas(8)` to align the generated array. This causes flat buffers to hard fault with an unaligned memory access (at least on my M4F device).

I guess the script should add that in front of the array?

**Comment by advaitjain** [comment]
Thanks for catching this bug. https://github.com/tensorflow/tflite-micro/pull/419 has the fix.
