### ISSUE TITLE
arduino esp32

### ISSUE THREAD

**Issue by FStefanni** [tensorflow/tflite-micro#439]
Hi,

I have noticed that (according with tutorials):
* For Arduino framework, only some Arduino boards are supported
* For ESP32, only the ESP-IDF framework is supported

Conversely, I usually program with the Arduino framework, targeting ESP32 boards.
I am wondering if there is a way to use this project with ESP32 but using the Arduino framework,
or if at least, you have plans to allow this in a near future.

Or, if I have to use this with Arduino, how can I do? Is there a starting point for the porting/integration?

Regards.

**Comment by advaitjain** [comment]
We do not have any plans to integrate the Arduino IDE with ESP32. The majority of the harware / platform support is community maintained and we certainly encourage more of that.

Here are a few links that might be useful:
 * https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/new_platform_support.md
 * https://github.com/tensorflow/tflite-micro-arduino-examples

Also, tagging @vikramdattu who is the maintainer of TFLM integration with ESP32.
