### ISSUE TITLE
Add uint8 test cases back for the detection post-process kernel

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tflite-micro#457]
With https://github.com/tensorflow/tflite-micro/pull/428 all uint8 support was removed from the TFLM kernels. However, detection_postprocess is a special case where we likely still need to support uint8.

Tagging @mansnils and @freddan80 for confirmation.

**Comment by mansnils** [comment]
@advaitjain We don't have any requirements for uint8 for this kernel. We might previously had a uint8 model that needed this but not anymore. So no changes needed, at least not from our side.

**Comment by advaitjain** [comment]
ok, thanks for the information. I'm going to close this bug without any changes then since our strong preference is to not have any uint8 support.

**Comment by advaitjain** [comment]
Cross-referencing an internal thread on this topic: https://chat.google.com/room/AAAAOhoX8KA/HqMY9uJ6RJc
