### ISSUE TITLE
Not possible to download third party software in a clean repo

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tflite-micro#460]
The creating of the download folder from the Makefile was probably removed by mistake. Now it is not possible to run make since the download script expects the download folder to be existing.

**Comment by advaitjain** [comment]
We had a bad merge which resulted in this regression.

Fixed with:
https://github.com/tensorflow/tflite-micro/commit/94ddbfe8ba348d56bc94486ee0120eb6e556fd98
