### ISSUE TITLE
micro: port op SLICE from lite 

### ISSUE THREAD

**Issue by annietllnd** [tensorflow/tflite-micro#467]
This issue tracks my work porting operator SLICE from lite to micro. It's an updated copy of [tensorflow/issues/51669](https://github.com/tensorflow/tensorflow/issues/51669)

The port will be submitted in a number of PRs, of which the first two are opened in the tensorflow repository. Here's a rough flight plan per @advaitjain:

[PR 1](https://github.com/tensorflow/tensorflow/pull/51670) (in Tensorflow repository): Extract the code for parsing the op from a flatbuffer out of ParseOpDataTfLite in tensorflow/lite/core/api/flatbuffer_conversions.cc into a standalone function that can be called from micro's op resolver
[PR 2](https://github.com/tensorflow/tensorflow/pull/51672) (in Tensorflow repository): Extract the reference implementation out of tensorflow/lite/kernels/internal/reference/reference_ops.h into its own header which can be included without dragging in reference_ops.h's dependences

PR 3: Copy operator from lite to micro without making any changes or including in the build
PR 4: Delete extra code from the micro copy of the operator
PR 5: Port micro copy of operator as necessary and add a corresponding test

**Comment by advaitjain** [comment]
Just an FYI that there was a high priority internal request to also port SLICE from tflite to TFLM and @njeffrie started with PR1 and PR2 that you have already merged and is most of the way to completing the port.

I hope that we didn't have too much duplicated effort. Please expect a PR with the SLICE op in the next couple of days.

**Comment by annietllnd** [comment]
Thanks for letting me know!

**Comment by annietllnd** [comment]
Hi @advaitjain and @njeffrie, how is this port coming along? Reason I'm asking is that I'm looking for learning opportunities once it is merged to compare with the work I did on the kernel. Thanks!

**Comment by njeffrie** [comment]
I've created  [this PR](https://github.com/tensorflow/tflite-micro/pull/568) with the slice operator.
