### ISSUE TITLE
Network context information from application to layer kernels

### ISSUE THREAD

**Issue by cad-audio** [tensorflow/tflite-micro#470]
@petewarden , @advaitjain ,
In the current framework, there is no network information available during layer kernel initialization and execution.
We do not see any issue with this mechanism for DSP solutions.
But for DSP with HW accelerator solutions, we see the need to have some network context available to layer kernel.
This network context would consist (not an exhaustive list)
- network identifier if more than one networks are simultaneously running
- Pointer to accelerator command stream for the network
- Initialization status of network with accelerator
- Runtime variables for performance optimization (IO buffer placement, order etc.) across layers
This context itself would not contain any command stream, coefficients or large metadata and its size would be limited.

[This PR](https://github.com/tensorflow/tflite-micro/pull/468) shows one experimental update to implement this. This uses tail of tensor arena buffer to save the network context.
It is application’s responsibility to allocate required, additional memory for this context and accelerator specific mapping code
in the layer kernel would interpret, use this information and it is not used / exposed to middle TFLM layers.

Please let us know your feedback.

**Comment by petewarden** [comment]
Thanks! I've taken a quick look, and one design principle we use is trying to follow TFLite mobile's path when possible. There's some work around external contexts here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/interpreter.h#L644
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/common.h#L53

How would this approach (not using the constructor, allowing multiple contexts, requiring context type registration) fit in with your needs?

**Comment by cad-audio** [comment]
Thanks @petewarden !
Please review the experimental [PR ](https://github.com/tensorflow/tflite-micro/pull/477) which uses external-context sharing as suggested above. Let me know your inputs and path forward.
