### ISSUE TITLE
Add 'Error' prefix to TF_LITE_REPORT_ERROR

### ISSUE THREAD

**Issue by freddan80** [tensorflow/tflite-micro#476]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): N/A
- Tensorflow version (commit SHA if source): 9578a394a0ebfa5f77f3e3b87f7b7fa266c97103
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Any

**Describe the problem**
It would be great if macro TF_LITE_REPORT_ERROR() prefixed the output with 'Error' or similar. That makes it easier for CI systems to parse for new issues. In a similar fashion, a macro TF_LITE_REPORT_WARNING() would be nice for warning. This could be a good location for the prefix:

```
#define TF_LITE_REPORT_ERROR(reporter, ...)                             \
  do {                                                                  \
    static_cast<tflite::ErrorReporter*>(reporter)->Report(__VA_ARGS__); \
  } while (false)
#else  // TF_LITE_STRIP_ERROR_STRINGS
#define TF_LITE_REPORT_ERROR(reporter, ...)
#endif  // TF_LITE_STRIP_ERROR_STRINGS
```
Let me know if there's a better way to achieve this.

**Please provide the exact sequence of commands/steps when you ran into the problem**
Any error print.

**Comment by advaitjain** [comment]
I'm going to close this issue since we're not planning on changes to the logging and error reporting at this time.
