### ISSUE TITLE
Issue With create_tflm_tree.py

### ISSUE THREAD

**Issue by embeddetech** [tensorflow/tflite-micro#504]
I am running an automated process that pulls TFLM into an existing VIsual Studio project. It was working before (a few weeks ago), but am seeing it break now.

The sequence is as follows:

- The repo is cloned into a temp folder
- I run python tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py, [destination folder]
- This eventually internally calls make -f "tensorflow\lite\micro\tools\make\Makefile" third_party_downloads, where an exception is thrown at line 225 of create_tflm_tree.py where make is run for this command.
- The Makefile loads and crashes in tensorflow/lite/micro/tools/generate_cc_arrays.py", line 26: from PIL import Image throws an error, ModuleNotFoundError: No module named 'PIL'. This python file appears to be called in tensorflow\lite\micro\tools\make\helper_functions.inc line 499

There are several articles about the PIL module not being found, and how to fix it by installing pillow. Does pillow need to be manually installed to replace PIL for tflite-micro?

Note; I just created an empty python file and added import PIL and ran it by itself, and it generates the same error. So there seems to be an issue with package setup, but this also doesn't seem to be inherently resolved by the automated build process.

**Comment by advaitjain** [comment]
Yes, pillow needs to be manually installed. And you might need Wave as well.

Here is where we have updated the CI to install these two dependencies:
https://github.com/tensorflow/tflite-micro/blob/1ef3830fa693bc5ab745100e53d55da97b4f8c29/.github/workflows/ci.yml#L40-L41

See related issue: https://github.com/tensorflow/tflite-micro/issues/401

**Comment by embeddetech** [comment]
Thank you, @advaitjain! So if I understand correctly, that action will only run on a pull request when building with bazel on ubuntu, is that correct? I can add this to my automation process.

**Comment by advaitjain** [comment]
Correct, I only linked to the workflow yml as an example of what you will need to do.

**Comment by embeddetech** [comment]
Update: 
I am using msys64 for make, and attempting to manually install Pillow in this global environment, using mintty with the command "python3 -m pip install Pillow". This command works fine when running in DOS which uses a different Python interpreter, but using the interpreter in msys64 seems to have issues caused by pip trying to build Pillow on the fly in a Windows environment as explained in this link:

https://github.com/python-pillow/Pillow/issues/2860

I am going to try to get Pillow installed without being built, just thought you might like to be aware of this potential issue building on Windows.
