### ISSUE TITLE
Add DIV function on all_ops_resolver

### ISSUE THREAD

**Issue by AlexisPapaioannou** [tensorflow/tflite-micro#513]
As the function DIV is not supported how can I add it?

**Comment by deqiangc** [comment]
Please take a look at https://github.com/tensorflow/tflite-micro/blob/main/CONTRIBUTING.md#reference-kernel-implementations.

Pull requests that port reference kernels from TF Lite Mobile to TF Lite Micro are welcome once we have context from the contributor on why the additional kernel is needed.

Every additional kernel requires maintenance and therefore contexts are important for us to understand the necessity of the new OP.
