### ISSUE TITLE
Didn't find op for builtin opcode 'SUM' version '2'. An older version of this builtin might be supported.

### ISSUE THREAD

**Issue by yugandharonchip** [tensorflow/tflite-micro#515]
Hi,

I built TFLM for xtensa hifi4 before tflite-micro stand-alone repo created and using those libraries only with i.MX RT 600 EVK which has Xtensa HiFi4 DSP.

During model initialization I got below error.
**Didn't find op for builtin opcode 'SUM' version '2'. An older version of this builtin might be supported.**

When I checked the [all_ops_resolver.cc](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/all_ops_resolver.cc) op 'SUM' is not available. This means the op 'SUM' is not yet supported in TFLM? Or will it work if I build TFLM again from new tflite-micro repo code?

I am getting similar error for op 'SquaredDifference' also.

The tensorflow code which generated op 'Sum' is **tf.math.reduce_sum** and op 'SquaredDifference' is **tf.keras.layers.LayerNormalization**. Is there any alternate to these two which can be worked with TFLM? Please suggest if anybody knows.

Thanks,
Yugandhar

**Comment by deqiangc** [comment]
SUM is not supported yet in the new repo.
Please take a look at 
https://github.com/tensorflow/tflite-micro/blob/main/CONTRIBUTING.md#reference-kernel-implementations.  

Pull requests that port reference kernels from TF Lite Mobile to TF Lite Micro are welcome once we have context from the contributor on why the additional kernel is needed.
