### ISSUE TITLE
No rule to make target 'tensorflow/lite/micro/tools/make/targets/arc_vpx_makefile.inc'

### ISSUE THREAD

**Issue by mohanish3795** [tensorflow/tflite-micro#527]
While building arc_mli, I am getting following error

Command given: make -f tensorflow/lite/micro/tools/make/Makefile TARGET=arc_vpx OPTIMIZED_KERNEL_DIR=arc_mli generate_person_detection_int8_make_project

Error : No rule to make target 'tensorflow/lite/micro/tools/make/targets/arc_vpx_makefile.inc' 

Looks like the arc_vpx_makefile.inc file is missing. 

@dzakhar @gerbauz

**Comment by gerbauz** [comment]
Hi @mohanish3795, sorry for the delay.

First of all, I temporary suggest to use our fork: https://github.com/foss-for-synopsys-dwc-arc-processors/tflite-micro, upstream version may not work.
Also, to build example for VPX, please use following instructions:
https://github.com/foss-for-synopsys-dwc-arc-processors/tflite-micro/tree/fork_main/tensorflow/lite/micro/examples/person_detection#generate-example-project-1

Regards,
Artem

**Comment by petewarden** [comment]
@gerbauz Let us know if you have a pull request pending to fix this in the main branch! I'll close this issue for now since there's a workaround.
