### ISSUE TITLE
Question regarding KWS and spectogram shape.

### ISSUE THREAD

**Issue by dsantiago** [tensorflow/tflite-micro#532]
The 30 ms windows, after the FFT generates 256 values. Then we group it in groups of six values and we now have 43 values.

The question is what about this value `constexpr int kFeatureSliceSize = 40;` in `micro_features_micro_model_settings.h`. I cannot understand how it works as the documentation in https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/micro_speech/train/README.md

**Comment by petewarden** [comment]
We don't group into exactly 6 values, instead there's a resampling process that takes neighboring values into account. The number of bins is ultimately set by `--feature_bin_count` in the training script:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/train.py#L403
