### ISSUE TITLE
TfLite Generating the project issue

### ISSUE THREAD

**Issue by aditi230** [tensorflow/tflite-micro#539]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): https://github.com/tensorflow/tflite-micro.git
- TensorFlow version (or github SHA if from source):

While running the command

make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project

facing the error as:
find: ‘../google/’: No such file or directory
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853d75de2af87622ad293ba" tensorflow/lite/micro/tools/make/downloads/gemmlowp  
The required 'curl' tool isn't installed. Try 'apt-get install curl'.
make: *** [tensorflow/lite/micro/tools/make/Makefile:583: tensorflow/lite/micro/tools/make/downloads/gemmlowp] Error 1

How Do I resolve this?

**Comment by advaitjain** [comment]
ESP32 is currently broken, please see https://github.com/tensorflow/tflite-micro/issues/458
