### ISSUE TITLE
 Non-maximum suppression function

### ISSUE THREAD

**Issue by AlexisPapaioannou** [tensorflow/tflite-micro#563]
Is there any way to add the non-maximum suppression function into the all_ops_resolver ?

**Comment by petewarden** [comment]
I believe it's already added, as DetectionPostProcess(), as shown here:

https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/all_ops_resolver.cc#L41

Closing this for now, but please reopen if I'm misunderstanding what you need.

**Comment by AlexisPapaioannou** [comment]
This function supports only the SSD model, until now?
