### ISSUE TITLE
Some make errors when "make -f tensorflow/lite/micro/tools/make/Makefile third_party_downloads"

### ISSUE THREAD

**Issue by RomanFoell** [tensorflow/tflite-micro#582]
Hi,

I get several errors " *** multiple target patterns.  Stop." in every line where, i.e.:

```
$(eval $(call microlite_test,micro_speech_mock,\
$(MICRO_SPEECH_MOCK_SRCS),$(MICRO_SPEECH_MOCK_HDRS),$(MICRO_SPEECH_GENERATOR_INPUTS)))
```

is written.

I solved it by writing:

```
$(eval $(call microlite_test,micro_speech_mock,\
$(MICRO_SPEECH_MOCK_SRCS),$(MICRO_SPEECH_MOCK_HDRS)))

$(eval $(call $(MICRO_SPEECH_GENERATOR_INPUTS)))
```

As said, this was in several Makefile.inc files.

Furthermore I found several typos, which stopped the make process, i.e. in

 tensorflow/lite/micro/examples/hello_world/Makefile.inc line 39 with double ",,":

`$(HELLO_WORLD_TEST_SRCS),,$(HELLO_WORLD_GENERATOR_INPUTS)))`

and in

/tensorflow/lite/micro/kernels/integration_tests/seanet/conv/Makefile.inc line 73 with double ",,":

`$(integration_tests_seanet_conv_SRCS),,$(integration_tests_seanet_conv_GENERATOR_INPUTS)))`

Perhaps there are more typos.

But it went through without problems then:

```
find: ‘../google/’: No such file or directory
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
make: Nothing to be done for 'third_party_downloads'.
```

Thanks

**Comment by advaitjain** [comment]
Similar to https://github.com/tensorflow/tflite-micro/issues/583, I am assuming that you are running into issues when attempting to build on Windows. We would be happy to review PRs with fixes, but are not able to support Windows at this time.
