### ISSUE TITLE
Node TFLite_Detection_PostProcess (number 63) failed to invoke with status 1

### ISSUE THREAD

**Issue by marcin-ch** [tensorflow/tflite-micro#595]
I am trying to run the object detection model available from here https://www.tensorflow.org/lite/examples/object_detection/overview on **NXP i.MXRT1170 (Cortex-M7)**, using **TensorFlow Lite for Microcontrollers** (this is from their [eIQ](https://www.nxp.com/design/software/development-software/eiq-ml-development-environment/eiq-inference-with-tensorflow-lite-micro:EIQ-TFLITE-MICRO) software to run machine learninig on MCUs/MPUs)

The model I mentioned contains custom operation *TFLite_Detection_PostProcess*:
| index | builtin_code                      | custom_code                        | version |
|-------|---------------------------|------------------------------|---------|
| 0       | CONV_2D                        |                                               | 1       |
| 1       | CONCATENATION            |                                               | 1       |
| 2       | DEPTHWISE_CONV_2D    |                                               | 1       |
| 3       | LOGISTIC                         |                                               | 1       |
| 4       | RESHAPE                          |                                               | 1       |
| 5       | CUSTOM                          | TFLite_Detection_PostProcess | 1       |

So, I did make following changes:
1. change resolver to `tflite::AllOpsResolver micro_op_resolver;`
2. in *all_ops_resolver.cpp* change `AddDetectionPostprocess();` to `AddTFLite_Detection_PostProcess();`
3. in *micro_mutable_op_resolver.h* change
```c
  TfLiteStatus AddDetectionPostprocess() {
    return AddCustom("TFLite_Detection_PostProcess",
                     tflite::Register_DETECTION_POSTPROCESS());
  }
```
to
```c
  TfLiteStatus AddTFLite_Detection_PostProcess() {
    return AddCustom("TFLite_Detection_PostProcess",
                     tflite::Register_TFLite_Detection_PostProcess());
  }
```
4. in the same file change `TfLiteRegistration* Register_DETECTION_POSTPROCESS();` to `TfLiteRegistration* Register_TFLite_Detection_PostProcess();`
5. in *detection_postprocess.cpp* at the end of file add
```cpp
TfLiteRegistration* Register_TFLite_Detection_PostProcess() {
	return Register_DETECTION_POSTPROCESS();
}
```

Output is:
```console
Node TFLite_Detection_PostProcess (number 63) failed to invoke with status 1
Invoke failed!
```

Do I miss something?

**Comment by advaitjain** [comment]
There is nothing obvious that I can see here. Similar to https://github.com/tensorflow/tflite-micro/issues/592, we would need a stand-alone reproduction case on x86 to give more concrete suggestions.
