### ISSUE TITLE
kernels/expand_dims.cc fault

### ISSUE THREAD

**Issue by driedler** [tensorflow/tflite-micro#597]
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/expand_dims.cc#L29

This causes a fault if the output Tensor is read-only (which it will be if the model is in flash).

I am not sure this is needed anyways as the TF-Lite Converter should have already configured the output tensor to be the right dimension.

Seems like there should just be a check to ensure the input/output are compatible and ExpandTensorDim() should only be used if the output tensor is writable.

As a work-around, I added:

```
  if(output_dims->size == input_dims->size + 1) {
    return kTfLiteOk;
  }
```

to the beginning of ExpandTensorDim()

**Comment by advaitjain** [comment]
Interesting observation and not something that I have an immediate answer to.

Only the model weights would be in flash, right? Not the activation buffers. Is it the case that the output tensor of expand dims is a weight tensor? Is there a model that you can share that illustrates the error that you are seeing?

I'm unsure what guarantees the converter provides. If you can provide a concrete example of the model where you are running into this issue, we can ask the question on [TfLite mailing list](https://groups.google.com/a/tensorflow.org/g/tflite) and get the experts on this topic to weigh in.
