### ISSUE TITLE
ARC target transition into platform specific repository.

### ISSUE THREAD

**Issue by gerbauz** [tensorflow/tflite-micro#637]
This issue will be used to track changes related to ARC specific files to meet requirements for moving hardware platform support and platform-specific customization of the examples out of the tflite-micro repository.

Related issue:
* [Move hardware / platform support to repositories that are external to tflite-micro #407](https://github.com/tensorflow/tflite-micro/issues/407)

**Comment by advaitjain** [comment]
Thanks for the heads up. Yes, we can help you make the transition prior to removing the ARC-specific code.

Having make/targets/arc is fine, with the caveat that the Makefile-based project generation will be removed. So any functionality in the tools/make/arc directory that depends on the Makefile-based project generation will have to be implemented differently.

Happy to discuss what the alternatives would be.

Ideally, there is a Linux tool chain that can be used to build and run the kernel tests without requiring any project generation, and only Makefiles needed for that are in the TFLM repository.

And everything that is not required for this Linux tool chain is in the ARC-specific examples repository.

**Comment by gerbauz** [comment]
Thank you for the answer.

> Ideally, there is a Linux tool chain that can be used to build and run the kernel tests without requiring any project generation, and only Makefiles needed for that are in the TFLM repository.
> 
> And everything that is not required for this Linux tool chain is in the ARC-specific examples repository.

Also, based on your [answer](https://github.com/tensorflow/tflite-micro/issues/407#issuecomment-956577367), for now, as we are not able to build using only Linux toolchain or using some options like docker image, we'll have to wait until external build systems will be integrated and only after that we can finally support kernel tests, right?

**Comment by gerbauz** [comment]
Hi @advaitjain,

As I see, xtensa using docker to run their tools, don't they?
https://github.com/tensorflow/tflite-micro/blob/1a23ad6adf007ad6ef3826523f41ff43fb686a13/.github/workflows/xtensa.yml#L38-L39

Can we look for same support for ARC target?

**Comment by gerbauz** [comment]
Hi @advaitjain,

Still interested in using docker for ARC tests. What do you think?

Thank you.
