### ISSUE TITLE
CMSIS-NN third party library builds with -Os flag.

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tflite-micro#638]
When building with OPTIMIZED_KERNEL_DIR=cmsis_nn, the glue code in tensorflow/lite/micro/kernels/cmsis_nn is built with the KERNEL_OPTIMIZATION_LEVEL=-O2.

The CMSIS-NN library are built as part of the THIRD_PARTY_OBJS, which is uses the optimization flag -Os (CORE_OPTIMIZATION_FLAG). It would be preferable to be able to specify a custom optimization flag for a third party library, since at least CMSIS-NN would see a performance increase when being compiled with for example -O3.

My initial thought is to add a CMSIS_NN_OPTIMIZATION_FLAG (or something to that effect) to [cmsis_nn.inc](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/tools/make/ext_libs/cmsis_nn.inc) which is then used in the Makefile, and to split the CMSIS-NN header-/source-files from the THIRD_PARTY_CC_HDRS/SRCS list into its own list.

But that solution would not scale well as the number of third party libraries and custom flags would increase, so it might be preferable to have a more complex, but scalable solution.

**Comment by jenselofsson** [comment]
@advaitjain @petewarden Do you have any thoughts on this?

**Comment by advaitjain** [comment]
Sorry for the delay here, we'll talk internally and get back to you on this.

Cross-linking https://github.com/tensorflow/tflite-micro/pull/774#discussion_r767025930
