### ISSUE TITLE
Transpose conv kernel wrapper has bugs

### ISSUE THREAD

**Issue by keandersslab** [tensorflow/tflite-micro#707]
The Prepare stage treats the kernel params as if it was is of type TfLiteConvParams. It should be TfLiteTransposeConvParam*. We then get arbitary values for dilation and activation. This leads to errors when calling ComputePaddingHeightWidth() and PopulateConvolutionQuantizationParams().

This patch is shows a sufficient solution:
[patch.txt](https://github.com/tensorflow/tflite-micro/files/7569046/patch.txt)

**Comment by petewarden** [comment]
Thanks @keandersslab ! I took a look at the patch and I see the issue. Would you be able to provide this as a pull request to make merging it easier? Having it as two separate PRs, one for this and another for #706 would help too.

Thanks again for your help improving the framework.

**Comment by keandersslab** [comment]
Sure Peter !

I doubt that I will have time right now to make test cases, but I will certainly be able provide pull requests by end of this week or early next week 😊

-Kjell Eirik Andersen
