### ISSUE TITLE
Port MIRROR_PAD from TFlite

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tflite-micro#741]
This issue tracks my work porting operator MIRROR_PAD from Tflite.

The port will be submitted in a number of PRs according to https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/porting_reference_ops.md - although PR2 won't be needed since the operator is not using anything from reference_ops.h.

**Comment by beekeeper23** [comment]
Thank you for your contribution! Is there any update or any timeline on your work?

**Comment by mansnils** [comment]
Hi @beekeeper23,
It is up for review now: https://github.com/tensorflow/tflite-micro/pull/779

**Comment by beekeeper23** [comment]
Perfect, thank you!
