### ISSUE TITLE
How to pass intermediate state to lstm in TFLM

### ISSUE THREAD

**Issue by JinmingChe** [tensorflow/tflite-micro#753]
How to explicitly pass in the intermediate state when deploying the lstm model in TFLM, this is how it is passed in TFLite
`# create states for the lstms
states_1 = np.zeros(input_details_1[1]['shape']).astype('float32')
states_2 = np.zeros(input_details_2[1]['shape']).astype('float32')`

How does TFLM create multiple inputs through interpreter.input?

Example only accept one input without state.
`// Get information about the memory area to use for the model's input.
TfLiteTensor* model_input = interpreter.input(0);`

Looking forward to your reply.

**Comment by yair-ehrenwald** [comment]
You can just use interpreter.input(1), interpreter.input(2) etc.

Same for outputs.

Haven't used this for LSTM but works fine with Keras GRUCell.
