### ISSUE TITLE
The data_type of tensor_arena

### ISSUE THREAD

**Issue by JinmingChe** [tensorflow/tflite-micro#756]
I have an uint8 quantized tflite model, how can it accept float tensor input.
The default tensor_arena type is uint8_t.
`MicroInterpreter(const Model* model, const MicroOpResolver& op_resolver,
                   uint8_t* tensor_arena, size_t tensor_arena_size,
                   ErrorReporter* error_reporter,
                   MicroResourceVariables* resource_variables = nullptr,
                   MicroProfiler* profiler = nullptr);`

The quantized tflite model we generated in python only accepts float input.

**Comment by deqiangc** [comment]
@advaitjain 
Hello, the "tensor" arena is just a contiguous memory that the framework can allocate memory for the model to run. It is not related with the type of input tensor.  Hence, it should not prevent your use case.

One improvement that I suppose that we can do to avoid this confusion is renaming tensor_arena to just arena. This may not be top of our improvement list although we would definitely keep that in mind.  

As there is no immediate action for us, I will close this issue.  Free free to re-open if you have further comments for this topic. Thanks!
