### ISSUE TITLE
ci mergify and test triggering refactor

### ISSUE THREAD

**Issue by jwithers** [tensorflow/tflite-micro#791]
We have been testing mergify as part of our CI pipeline. Unfortunately, getting it to trigger tests correctly in queue has been an issue.
When mergify puts a PR in the merge queue, the first thing that happens is that if it is behind main, main is merged into the PR branch. This causes all the test conditions to reset.
Our test conditions are run using the label ci:run. This label deletes itself after launching the github action test suite and that is expected behavior from the users. However, with that tag being deleted, when the test conditions are reset in queue the PR stalls because the now-deleted tag is required to trigger the test suite. In a long queue, the number of times the tag would need to be manually reapplied is queue.length - 1. 
The addition of the ci:ready_to_merge label, which doesn't self delete until the pr is merged into main, provided a solution for this, but required adding a lot of label test condition lines to our github action scripts and the conditional section of those scripts is getting to be a small chunk of boilerplate.

@advaitjain had the smart idea that this should be refactored to a single script firing on the PULL_REQUEST_TARGET[synchronize] trigger which adds the ci-run tag. Synchronize fires when a PR has a commit added or main merged in, so it should add the tag that starts the testing in our problem case.

In a perfect world that script would also check for an approved review to prevent spurious test runs from pr update commits, but unfortunately the github machinery makes that hard to do from the particular trigger we are using. Still looking for a good solution for that bit.

And while we are here we should also trigger a review approval just adding the ci:run label to a PR, because there isn't an obvious use case where a review approval doesn't want a run of the test suite.

**Comment by advaitjain** [comment]
internal bug: http://b/210910354
