### ISSUE TITLE
What is the maximum tflite file size?

### ISSUE THREAD

**Issue by MATTYGILO** [tensorflow/tflite-micro#822]
I was wondering what the maximum tflite file size is on tflite-micro?

**Comment by advaitjain** [comment]
There isn;t any limit on the model size imposed by the TFLM framework itself. It really comes down to the target platform and how much memory you can allocate for the TFLM arena.

**Comment by advaitjain** [comment]
Please see https://github.com/tensorflow/tflite-micro/issues/823#issuecomment-1003678182 for a more detailed discussion on this topic.
