### ISSUE TITLE
DetectionPostprocessFloatRegularNMS hangs for target cortex_m_corstone_300 on Cortex-M55

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tflite-micro#847]
EDITED 2022-01-27 for accuracy

The hang occurs for the testcase [DetectionPostprocessFloatRegularNMS](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/detection_postprocess.cc#L118) in the [Init-function](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/detection_postprocess.cc#L118) when trying to access element at "nms_score_threshold" in the flexbuffers map m.

It also seems to happen when trying to access the following elements in the same map:
nms_iou_threshold
y_scale
x_scale
h_scale
w_scale

The hang occurs in the [ReadScalar-function](https://github.com/google/flatbuffers/blob/master/include/flatbuffers/base.h#L406) in the flatbuffer library, when p is dereferenced. The hang occurs due to a HardFault due to unaligned access. This makes me think that the issue-report might belong more in the flatbuffers-issue tracker.

Steps to reproduce:
Apply this patch which removes the fix for this issue:
https://github.com/jenselofsson/tflite-micro/commit/f70fbce65f1bdb230f62389fd1e7c305ddfbd8de

$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=cortex_m_corstone_300 TARGET_ARCH=cortex-m55 test_kernel_detection_postprocess_test

**Comment by jenselofsson** [comment]
I seemed to have spoken too soon, I had some local changes laying about which gave a different result. The new results are that GCC works fine, but hangs for armclang for at least -O0, -O1, -O2, -O3.

**Comment by annietllnd** [comment]
Hi, here's an update for this issue: Having a look at the hardcoded buffers [g_gen_data_size_non_regular_nms and g_gen_data_size_regular_nms](https://github.com/tensorflow/tflite-micro/blob/89c40b27c6b8ca031012e5b874486988bff00d1a/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.cc), that are next to each other in memory, we discover that they're char* buffers, with a size of 242 (which is not divisible by 4, the size of a word). The flatbuffer project does not check for alignment. And when the parameter CORE_OPTIMIZATION_LEVEL != -O2, we optimize for size. This means that the second buffer (g_gen_data_size_regular_nms) will be squished and end up over two words, which is believed causes the hang. We will submit a solution where we've added alignas(4) for both of the buffers.

**Comment by annietllnd** [comment]
Hi, this issue falls under #274
