### ISSUE TITLE
CMSIS DepthwiseConv2d Kernels doesn't use fused activation

### ISSUE THREAD

**Issue by driedler** [tensorflow/tflite-micro#875]
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/cmsis_nn/depthwise_conv.cc#L172

```
  // TODO(b/130439627): Use calculated value for clamping.
  dw_conv_params.activation.min = std::numeric_limits<int8_t>::min();
  dw_conv_params.activation.max = std::numeric_limits<int8_t>::max();
```

This effectively disables the ReLU activation in DepthwiseConv2D (which is a majority of the layers in MobileNetV1)

IMO, if this can't be fixed then it should default to the reference kernel.

**Comment by mansnils** [comment]
Hi @driedler 
Thanks for raising this. We will look into it.
