### ISSUE TITLE
Support for ESP32-C3 and ESP32-S3 ?

### ISSUE THREAD

**Issue by mtk11** [tensorflow/tflite-micro#919]
Interested about running tflite-micro on [ESP32-C3](https://www.espressif.com/en/products/socs/esp32-c3) and [ESP32-S3.](https://www.espressif.com/en/products/socs/esp32-s3) Are they supported ? ESP32-S3 is advertised to have AI optimized instructions.

**Comment by vikramdattu** [comment]
@mtk11 please find the repo [here](https://github.com/espressif/tflite-micro-esp-examples) with Espressif chipsets support.

This indeed has instructions level optimisations for `ESP32-S3` and general `ANSI C` optimisations in general.

**Comment by RostakaGmfun** [comment]
Hi @vikramdattu, do you plan to contribute this port to the upstream?

**Comment by hadrien-toma** [comment]
😊 it would still be useful on my side

**Comment by vikramdattu** [comment]
@hadrien-toma as I have commented, the support is already available in [this](https://github.com/espressif/tflite-micro-esp-examples) repo.  The repo is periodically kept in sync with tflite-micro. 

What changes having in upstream are useful to you? This isn't planned to be honest. If this indeed looks useful, I can prioritise.

**Comment by hadrien-toma** [comment]
Aw sorry @vikramdattu, thank you very much, the repo you mentioned seems to be perfect for my use case! Thanks again ❤️
