### ISSUE TITLE
Porting Reference LSTM Op from Lite to Micro

### ISSUE THREAD

**Issue by tingyan19** [tensorflow/tflite-micro#920]
This issue is to track efforts to port the reference LSTM kernel from TF Lite to TFLM.

**Comment by tingyan19** [comment]
following instructions in https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/porting_reference_ops.md

**Comment by christophsiegl** [comment]
What is the current status of the implementation? The unidirectionalSequenceLSTM is still missing in all_ops_resolver.cc ?
