### ISSUE TITLE
Failure in Ethos regression after enforcing all AllocateTemp must be paired with DeallocateTemp

### ISSUE THREAD

**Issue by deqiangc** [tensorflow/tflite-micro#953]
Hi team

We ran into an issue during our nightly regression. The issue is due to commit 05b427e1 and stems from the added error check:

https://github.com/tensorflow/tflite-micro/blob/47c8748c52f490d9270f3905f145102dd60d41a2/tensorflow/lite/micro/simple_memory_allocator.cc#L142-L145

I think you'll see the issue in your nightly tests as well. If not, it can be reproduced with:

make -j -f tensorflow/lite/micro/tools/make/Makefile TARGET=cortex_m_corstone_300 OPTIMIZED_KERNEL_DIR=cmsis_nn CO_PROCESSOR=ethos_u TARGET_ARCH=cortex-m55 test_network_tester_test

The error message is:

Number of allocated temp buffers: 1. Checksum passing status: 0
All temp buffers must be freed before calling ResetTempAllocations()

The issue is related to running an Ethos-U model, therefore I guess that is has something to do with offline memory plan. I'm not sure why there's still a temp buffer left in this case. Do you mind having a look at this issue?

Cheers,
Fredrik

**Comment by freddan80** [comment]
@deqiangc this is ready to close
